//---[Ambiente de DESTINO]
const cat001 = [
  { Codigo: "00", Valores: "Modo Prueba" },
  { Codigo: "01", Valores: "Modo Producción" },
];

//---[Tipo de documento electrónico]
const cat002 = [
    {Codigo:"01",   Valores:"Factura Electrónica",  Abreviatura: "FE"	},	
    {Codigo:"03",   Valores:"Comprobante de Crédito Fiscal Electrónico"	,Abreviatura:"CCFE"	},	
    {Codigo:"04",   Valores:"Nota de Remisión Electrónico"	,Abreviatura:"NRE"	},	
    {Codigo:"05",   Valores:"Nota de Crédito Electrónico"	,Abreviatura:"NCE"	},	
    {Codigo:"06",   Valores:"Nota de Débito Electrónico"	,Abreviatura:"NDE"	},	
    {Codigo:"07",   Valores:"Comprobante de Retención Electrónico"	,Abreviatura:"CRE"	},	
    {Codigo:"08",   Valores:"Comprobante de Liquidación Electrónico"	,Abreviatura:"CLE"	},	
    {Codigo:"09",   Valores:"Documento Contable de Liquidación Electrónico"	,Abreviatura:"DCLE"	},	
    {Codigo:"11",   Valores:"Factura de Exportación Electrónico"	,Abreviatura:"FEXE"	},	
    {Codigo:"14",   Valores:"Factura de Sujeto Excluido Electrónica"	,Abreviatura:"FSEE"	},	
    {Codigo:"15",   Valores:"Comprobante de Donación Electrónico"	,Abreviatura:"CDE"	},
];

//---[Módelo de Facturación]
const cat003 = [
    { Codigo: 1, Valores: "Modelo Facturación previo" },
    { Codigo: 2, Valores: "Modelo Facturación diferido" },
];

//---[Tipo de transmisión]
const cat004 = [
    { Codigo: 1, Valores: "Transmisión normal" },
    { Codigo: 2, Valores: "Transmisión por contingencia" },
];

//---[Tipo de contingencia]
const cat005 = [
    { Codigo: 1, Valores: "No disponibilidad de sistema del MH" },
    { Codigo: 2, Valores: "No disponibilidad de sistema del emisor" },
	{ Codigo: 3, Valores: "Falla en el suministro de servicio de Internet del Emisor" },
	{ Codigo: 4, Valores: "Falla en el suministro de servicio de energía eléctrica del emisor que impida la transmisión de los DTE " },
	{ Codigo: 5, Valores: "Otro (deberá digitar un máximo de 500 caracteres explicando el motivo)" },
];

//---[Retención IVA MH]
const cat006 = [
    { Codigo: "22", Valores: "Retención IVA 1%" },
    { Codigo: "C4", Valores: "Retención IVA 13% " },
	{ Codigo: "C9", Valores: "Otras retenciones IVA casos especiales" },

];

//---[Tipo de Generación del Documento ]
const cat007 = [
    { Codigo: 1, Valores: "Físico" },
    { Codigo: 2, Valores: "Electrónico" },
];

//---[Tipo de establecimiento]
//  { id: 187, Codigo: "9300", Valores: "EL SALVADOR" },
const cat009 = [
  { id: 1, Codigo: "01", Valores: "Sucursal / Agencia" },
  { id: 2, Codigo: "02", Valores: "Casa matriz" },
  { id: 3, Codigo: "04", Valores: "Bodega" },
  { id: 4, Codigo: "07", Valores: "Predio y/o patio" },
  { id: 5, Codigo: "20", Valores: "Otro" },
];

//---[CAT-010 Código tipo de Servicio (Médico)]
const cat010 = [
  { Codigo: 1, Valores: "Cirugía" },
  { Codigo: 2, Valores: "Operación" },
  { Codigo: 3, Valores: "Tratamiento médico" },
  { Codigo: 4, Valores: "Cirugía instituto salvadoreño de Bienestar Magisterial" },
  { Codigo: 5, Valores: "Operación Instituto Salvadoreño de Bienestar Magisterial" },
  { Codigo: 6, Valores: "Tratamiento médico Instituto Salvadoreño de Bienestar Magisterial" },
];

//---[TIPO DE ÍTEM]
const cat011 = [
  { id: 1, Codigo: "1", Valores: "Bienes" },
  { id: 2, Codigo: "2", Valores: "Servicios" },
  { id: 3, Codigo: "3", Valores: "Ambos" }, //(Bienes y Servicios, incluye los dos inherente a los Productos o servicios)
  { id: 4, Codigo: "4", Valores: "Otros tributos por ítem" },
];

//---[DEPARTAMENTO]
const cat012 = [
  { id: 0, Codigo: "00", Valores: "Otro País" },
  { id: 1, Codigo: "01", Valores: "AHUACHAPÁN" },
  { id: 2, Codigo: "02", Valores: "SANTA ANA" },
  { id: 3, Codigo: "03", Valores: "SONSONATE" },
  { id: 4, Codigo: "04", Valores: "CHALATENANGO" },
  { id: 5, Codigo: "05", Valores: "LA LIBERTAD" },
  { id: 6, Codigo: "06", Valores: "SAN SALVADOR" },
  { id: 7, Codigo: "07", Valores: "CUSCATLÁN" },
  { id: 8, Codigo: "08", Valores: "LA PAZ" },
  { id: 9, Codigo: "09", Valores: "CABAÑAS" },
  { id: 10, Codigo: "10", Valores: "SAN VIVENTE" },
  { id: 11, Codigo: "11", Valores: "USULUTÁN" },
  { id: 12, Codigo: "12", Valores: "SAN MIGUEL" },
  { id: 13, Codigo: "13", Valores: "MORAZÁN" },
  { id: 14, Codigo: "14", Valores: "LA UNIÓN" },
];

//---[MUNICIPIOS]
const cat013 = [
  { id: 0, Codigo: "00", Valores: "Otro País", Departamento: "00" },
  { id: 1, Codigo: "01", Valores: "AHUACHAPÁN", Departamento: "01" },
  { id: 2, Codigo: "02", Valores: "APANECA ", Departamento: "01" },
  { id: 3, Codigo: "03", Valores: "ATIQUIZAYA", Departamento: "01" },
  { id: 4, Codigo: "04", Valores: "CONCEPCIÓN DE ATACO ", Departamento: "01" },
  { id: 5, Codigo: "05", Valores: "EL REFUGIO ", Departamento: "01" },
  { id: 6, Codigo: "06", Valores: "GUAYMANGO", Departamento: "01" },
  { id: 7, Codigo: "07", Valores: "JUJUTLA", Departamento: "01" },
  { id: 8, Codigo: "08", Valores: "SAN FRANCISCO MENÉNDEZ", Departamento: "01" },
  { id: 9, Codigo: "09", Valores: "SAN LORENZO", Departamento: "01" },
  { id: 10, Codigo: "10", Valores: "SAN PEDRO PUXTLA", Departamento: "01" },
  { id: 11, Codigo: "11", Valores: "TACUBA", Departamento: "01" },
  { id: 12, Codigo: "12", Valores: "TURÍN", Departamento: "01" },
  { id: 13, Codigo: "01", Valores: "CANDELARIA DE LA FRONTERA", Departamento: "02" },
  { id: 14, Codigo: "02", Valores: "COATEPEQUE", Departamento: "02" },
  { id: 15, Codigo: "03", Valores: "CHALCHUAPA", Departamento: "02" },
  { id: 16, Codigo: "04", Valores: "EL CONGO", Departamento: "02" },
  { id: 17, Codigo: "05", Valores: "EL PORVENIR", Departamento: "02" },
  { id: 18, Codigo: "06", Valores: "MASAHUAT", Departamento: "02" },
  { id: 19, Codigo: "07", Valores: "METAPÁN ", Departamento: "02" },
  { id: 20, Codigo: "08", Valores: "SAN ANTONIO PAJONAL ", Departamento: "02" },
  { id: 21, Codigo: "09", Valores: "SAN SEBASTIÁN SALITRILLO", Departamento: "02" },
  { id: 22, Codigo: "10", Valores: "SANTA ANA", Departamento: "02" },
  { id: 23, Codigo: "11", Valores: "STA ROSA GUACHI ", Departamento: "02" },
  { id: 24, Codigo: "12", Valores: "STGO D LA FRONT", Departamento: "02" },
  { id: 25, Codigo: "13", Valores: "TEXISTEPEQUE", Departamento: "02" },
  { id: 26, Codigo: "01", Valores: "ACAJUTLA", Departamento: "03" },
  { id: 27, Codigo: "02", Valores: "ARMENIA", Departamento: "03" },
  { id: 28, Codigo: "03", Valores: "CALUCO ", Departamento: "03" },
  { id: 29, Codigo: "04", Valores: "CUISNAHUAT", Departamento: "03" },
  { id: 30, Codigo: "05", Valores: "STA I ISHUATAN", Departamento: "03" },
  { id: 31, Codigo: "06", Valores: "IZALCO", Departamento: "03" },
  { id: 32, Codigo: "07", Valores: "JUAYÚA", Departamento: "03" },
  { id: 33, Codigo: "08", Valores: "NAHUIZALCO", Departamento: "03" },
  { id: 34, Codigo: "09", Valores: "NAHULINGO", Departamento: "03" },
  { id: 35, Codigo: "10", Valores: "SALCOATITÁN", Departamento: "03" },
  { id: 36, Codigo: "11", Valores: "SAN ANTONIO DEL MONTE", Departamento: "03" },
  { id: 37, Codigo: "12", Valores: "SAN JULIÁN", Departamento: "03" },
  { id: 38, Codigo: "13", Valores: "STA C MASAHUAT", Departamento: "03" },
  { id: 39, Codigo: "14", Valores: "SANTO DOMINGO GUZMÁN", Departamento: "03" },
  { id: 40, Codigo: "15", Valores: "SONSONATE", Departamento: "03" },
  { id: 41, Codigo: "16", Valores: "SONZACATE ", Departamento: "03" },
  { id: 42, Codigo: "01", Valores: "AGUA CALIENTE", Departamento: "04" },
  { id: 43, Codigo: "02", Valores: "ARCATAO", Departamento: "04" },
  { id: 44, Codigo: "03", Valores: "AZACUALPA", Departamento: "04" },
  { id: 45, Codigo: "04", Valores: "CITALÁ", Departamento: "04" },
  { id: 46, Codigo: "05", Valores: "COMALAPA", Departamento: "04" },
  { id: 47, Codigo: "06", Valores: "CONCEPCIÓN QUEZALTEPEQUE", Departamento: "04" },
  { id: 48, Codigo: "07", Valores: "CHALATENANGO", Departamento: "04" },
  { id: 49, Codigo: "08", Valores: "DULCE NOM MARÍA ", Departamento: "04" },
  { id: 50, Codigo: "09", Valores: "EL CARRIZAL", Departamento: "04" },
  { id: 51, Codigo: "10", Valores: "EL PARAÍSO", Departamento: "04" },
  { id: 52, Codigo: "11", Valores: "LA LAGUNA", Departamento: "04" },
  { id: 53, Codigo: "12", Valores: "LA PALMA", Departamento: "04" },
  { id: 54, Codigo: "13", Valores: "LA REINA", Departamento: "04" },
  { id: 55, Codigo: "14", Valores: "LAS VUELTAS", Departamento: "04" },
  { id: 56, Codigo: "15", Valores: "NOMBRE DE JESUS", Departamento: "04" },
  { id: 57, Codigo: "16", Valores: "NVA CONCEPCIÓN", Departamento: "04" },
  { id: 58, Codigo: "17", Valores: "NUEVA TRINIDAD", Departamento: "04" },
  { id: 59, Codigo: "18", Valores: "OJOS DE AGUA", Departamento: "04" },
  { id: 60, Codigo: "19", Valores: "POTONICO", Departamento: "04" },
  { id: 61, Codigo: "20", Valores: "SAN ANT LA CRUZ", Departamento: "04" },
  { id: 62, Codigo: "21", Valores: "SAN ANT RANCHOS", Departamento: "04" },
  { id: 63, Codigo: "22", Valores: "SAN FERNANDO", Departamento: "04" },
  { id: 64, Codigo: "23", Valores: "SAN FRANCISCO LEMPA", Departamento: "04" },
  { id: 65, Codigo: "24", Valores: "SAN FRANCISCO MORAZÁN", Departamento: "04" },
  { id: 66, Codigo: "25", Valores: "SAN IGNACIO", Departamento: "04" },
  { id: 67, Codigo: "26", Valores: "SAN I LABRADOR", Departamento: "04" },
  { id: 68, Codigo: "27", Valores: "SAN J CANCASQUE", Departamento: "04" },
  { id: 69, Codigo: "28", Valores: "SAN JOSE FLORES", Departamento: "04" },
  { id: 70, Codigo: "29", Valores: "SAN LUIS CARMEN", Departamento: "04" },
  { id: 71, Codigo: "30", Valores: "SN MIG MERCEDES", Departamento: "04" },
  { id: 72, Codigo: "31", Valores: "SAN RAFAEL", Departamento: "04" },
  { id: 73, Codigo: "32", Valores: "SANTA RITA", Departamento: "04" },
  { id: 74, Codigo: "33", Valores: "TEJUTLA", Departamento: "04" },
  { id: 75, Codigo: "01", Valores: "ANTGO CUSCATLÁN", Departamento: "05" },
  { id: 76, Codigo: "02", Valores: "CIUDAD ARCE", Departamento: "05" },
  { id: 77, Codigo: "03", Valores: "COLON", Departamento: "05" },
  { id: 78, Codigo: "04", Valores: "COMASAGUA", Departamento: "05" },
  { id: 79, Codigo: "05", Valores: "CHILTIUPAN", Departamento: "05" },
  { id: 80, Codigo: "06", Valores: "HUIZÚCAR ", Departamento: "05" },
  { id: 81, Codigo: "07", Valores: "JAYAQUE", Departamento: "05" },
  { id: 82, Codigo: "08", Valores: "JICALAPA", Departamento: "05" },
  { id: 83, Codigo: "09", Valores: "LA LIBERTAD", Departamento: "05" },
  { id: 84, Codigo: "10", Valores: "NUEVO CUSCATLÁN", Departamento: "05" },
  { id: 85, Codigo: "11", Valores: "SANTA TECLA", Departamento: "05" },
  { id: 86, Codigo: "12", Valores: "QUEZALTEPEQUE", Departamento: "05" },
  { id: 87, Codigo: "13", Valores: "SACACOYO", Departamento: "05" },
  { id: 88, Codigo: "14", Valores: "SN J VILLANUEVA", Departamento: "05" },
  { id: 89, Codigo: "15", Valores: "SAN JUAN OPICO", Departamento: "05" },
  { id: 90, Codigo: "16", Valores: "SAN MATÍAS", Departamento: "05" },
  { id: 91, Codigo: "17", Valores: "SAN P TACACHICO", Departamento: "05" },
  { id: 92, Codigo: "18", Valores: "TAMANIQUE", Departamento: "05" },
  { id: 93, Codigo: "19", Valores: "TALNIQUE", Departamento: "05" },
  { id: 94, Codigo: "20", Valores: "TEOTEPEQUE", Departamento: "05" },
  { id: 95, Codigo: "21", Valores: "TEPECOYO", Departamento: "05" },
  { id: 96, Codigo: "22", Valores: "ZARAGOZA", Departamento: "05" },
  { id: 97, Codigo: "01", Valores: "AGUILARES ", Departamento: "06" },
  { id: 98, Codigo: "02", Valores: "APOPA", Departamento: "06" },
  { id: 99, Codigo: "03", Valores: "AYUTUXTEPEQUE", Departamento: "06" },
  { id: 100, Codigo: "04", Valores: "CUSCATANCINGO", Departamento: "06" },
  { id: 101, Codigo: "05", Valores: "EL PAISNAL", Departamento: "06" },
  { id: 102, Codigo: "06", Valores: "GUAZAPA", Departamento: "06" },
  { id: 103, Codigo: "07", Valores: "ILOPANGO", Departamento: "06" },
  { id: 104, Codigo: "08", Valores: "MEJICANOS", Departamento: "06" },
  { id: 105, Codigo: "09", Valores: "NEJAPA", Departamento: "06" },
  { id: 106, Codigo: "10", Valores: "PANCHIMALCO", Departamento: "06" },
  { id: 107, Codigo: "11", Valores: "ROSARIO DE MORA", Departamento: "06" },
  { id: 108, Codigo: "12", Valores: "SAN MARCOS", Departamento: "06" },
  { id: 109, Codigo: "13", Valores: "SAN MARTIN", Departamento: "06" },
  { id: 110, Codigo: "14", Valores: "SAN SALVADOR", Departamento: "06" },
  { id: 111, Codigo: "15", Valores: "STG TEXACUANGOS", Departamento: "06" },
  { id: 112, Codigo: "16", Valores: "SANTO TOMAS", Departamento: "06" },
  { id: 113, Codigo: "17", Valores: "SOYAPANGO", Departamento: "06" },
  { id: 114, Codigo: "18", Valores: "TONACATEPEQUE", Departamento: "06" },
  { id: 115, Codigo: "19", Valores: "CIUDAD DELGADO", Departamento: "06" },
  { id: 116, Codigo: "01", Valores: "CANDELARIA", Departamento: "07" },
  { id: 117, Codigo: "02", Valores: "COJUTEPEQUE", Departamento: "07" },
  { id: 118, Codigo: "03", Valores: "EL CARMEN", Departamento: "07" },
  { id: 119, Codigo: "04", Valores: "EL ROSARIO", Departamento: "07" },
  { id: 120, Codigo: "05", Valores: "MONTE SAN JUAN", Departamento: "07" },
  { id: 121, Codigo: "06", Valores: "ORAT CONCEPCIÓN", Departamento: "07" },
  { id: 122, Codigo: "07", Valores: "SAN B PERULAPIA", Departamento: "07" },
  { id: 123, Codigo: "08", Valores: "SAN CRISTÓBAL", Departamento: "07" },
  { id: 124, Codigo: "09", Valores: "SAN J GUAYABAL", Departamento: "07" },
  { id: 125, Codigo: "10", Valores: "SAN P PERULAPÁN", Departamento: "07" },
  { id: 126, Codigo: "11", Valores: "SAN RAF CEDROS", Departamento: "07" },
  { id: 127, Codigo: "12", Valores: "SAN RAMON", Departamento: "07" },
  { id: 128, Codigo: "13", Valores: "STA C ANALQUITO", Departamento: "07" },
  { id: 129, Codigo: "14", Valores: "STA C MICHAPA", Departamento: "07" },
  { id: 130, Codigo: "15", Valores: "SUCHITOTO", Departamento: "07" },
  { id: 131, Codigo: "16", Valores: "TENANCINGO", Departamento: "07" },
  { id: 132, Codigo: "01", Valores: "CUYULTITÁN", Departamento: "08" },
  { id: 133, Codigo: "02", Valores: "EL ROSARIO", Departamento: "08" },
  { id: 134, Codigo: "03", Valores: "JERUSALÉN", Departamento: "08" },
  { id: 135, Codigo: "04", Valores: "MERCED LA CEIBA", Departamento: "08" },
  { id: 136, Codigo: "05", Valores: "OLOCUILTA", Departamento: "08" },
  { id: 137, Codigo: "06", Valores: "PARAÍSO OSORIO", Departamento: "08" },
  { id: 138, Codigo: "07", Valores: "SN ANT MASAHUAT", Departamento: "08" },
  { id: 139, Codigo: "08", Valores: "SAN EMIGDIO", Departamento: "08" },
  { id: 140, Codigo: "09", Valores: "SN FCO CHINAMEC", Departamento: "08" },
  { id: 141, Codigo: "10", Valores: "SAN J NONUALCO", Departamento: "08" },
  { id: 142, Codigo: "11", Valores: "SAN JUAN TALPA", Departamento: "08" },
  { id: 143, Codigo: "12", Valores: "SAN JUAN TEPEZONTES", Departamento: "08" },
  { id: 144, Codigo: "13", Valores: "SAN LUIS TALPA", Departamento: "08" },
  { id: 145, Codigo: "14", Valores: "SAN MIGUEL TEPEZONTES", Departamento: "08" },
  { id: 146, Codigo: "15", Valores: "SAN PEDRO MASAHUAT", Departamento: "08" },
  { id: 147, Codigo: "16", Valores: "SAN PEDRO NONUALCO", Departamento: "08" },
  { id: 148, Codigo: "17", Valores: "SAN R OBRAJUELO", Departamento: "08" },
  { id: 149, Codigo: "18", Valores: "STA MA OSTUMA", Departamento: "08" },
  { id: 150, Codigo: "19", Valores: "STGO NONUALCO", Departamento: "08" },
  { id: 151, Codigo: "20", Valores: "TAPALHUACA", Departamento: "08" },
  { id: 152, Codigo: "21", Valores: "ZACATECOLUCA", Departamento: "08" },
  { id: 153, Codigo: "22", Valores: "SN LUIS LA HERR", Departamento: "08" },
  { id: 154, Codigo: "01", Valores: "CINQUERA", Departamento: "09" },
  { id: 155, Codigo: "02", Valores: "GUACOTECTI", Departamento: "09" },
  { id: 156, Codigo: "03", Valores: "ILOBASCO", Departamento: "09" },
  { id: 157, Codigo: "04", Valores: "JUTIAPA", Departamento: "09" },
  { id: 158, Codigo: "05", Valores: "SAN ISIDRO ", Departamento: "09" },
  { id: 159, Codigo: "06", Valores: "SENSUNTEPEQUE", Departamento: "09" },
  { id: 160, Codigo: "07", Valores: "TEJUTEPEQUE", Departamento: "09" },
  { id: 161, Codigo: "08", Valores: "VICTORIA", Departamento: "09" },
  { id: 162, Codigo: "09", Valores: "DOLORES", Departamento: "09" },
  { id: 163, Codigo: "01", Valores: "APASTEPEQUE", Departamento: "10" },
  { id: 164, Codigo: "02", Valores: "GUADALUPE", Departamento: "10" },
  { id: 165, Codigo: "03", Valores: "SAN CAY ISTEPEQ", Departamento: "10" },
  { id: 166, Codigo: "04", Valores: "SANTA CLARA", Departamento: "10" },
  { id: 167, Codigo: "05", Valores: "SANTO DOMINGO", Departamento: "10" },
  { id: 168, Codigo: "06", Valores: "SN EST CATARINA", Departamento: "10" },
  { id: 169, Codigo: "07", Valores: "SAN ILDEFONSO", Departamento: "10" },
  { id: 170, Codigo: "08", Valores: "SAN LORENZO", Departamento: "10" },
  { id: 171, Codigo: "09", Valores: "SAN SEBASTIÁN", Departamento: "10" },
  { id: 172, Codigo: "10", Valores: "SAN VICENTE", Departamento: "10" },
  { id: 173, Codigo: "11", Valores: "TECOLUCA", Departamento: "10" },
  { id: 174, Codigo: "12", Valores: "TEPETITÁN", Departamento: "10" },
  { id: 175, Codigo: "13", Valores: "VERAPAZ ", Departamento: "10" },
  { id: 176, Codigo: "01", Valores: "ALEGRÍA ", Departamento: "11" },
  { id: 177, Codigo: "02", Valores: "BERLÍN ", Departamento: "11" },
  { id: 178, Codigo: "03", Valores: "CALIFORNIA", Departamento: "11" },
  { id: 179, Codigo: "04", Valores: "CONCEP BATRES", Departamento: "11" },
  { id: 180, Codigo: "05", Valores: "EL TRIUNFO", Departamento: "11" },
  { id: 181, Codigo: "06", Valores: "EREGUAYQUÍN", Departamento: "11" },
  { id: 182, Codigo: "07", Valores: "ESTANZUELAS", Departamento: "11" },
  { id: 183, Codigo: "08", Valores: "JIQUILISCO", Departamento: "11" },
  { id: 184, Codigo: "09", Valores: "JUCUAPA", Departamento: "11" },
  { id: 185, Codigo: "10", Valores: "JUCUARÁN", Departamento: "11" },
  { id: 186, Codigo: "11", Valores: "MERCEDES UMAÑA", Departamento: "11" },
  { id: 187, Codigo: "12", Valores: "NUEVA GRANADA", Departamento: "11" },
  { id: 188, Codigo: "13", Valores: "OZATLÁN", Departamento: "11" },
  { id: 189, Codigo: "14", Valores: "PTO EL TRIUNFO", Departamento: "11" },
  { id: 190, Codigo: "15", Valores: "SAN AGUSTÍN ", Departamento: "11" },
  { id: 191, Codigo: "16", Valores: "SN BUENAVENTURA", Departamento: "11" },
  { id: 192, Codigo: "17", Valores: "SAN DIONISIO ", Departamento: "11" },
  { id: 193, Codigo: "18", Valores: "SANTA ELENA", Departamento: "11" },
  { id: 194, Codigo: "19", Valores: "SAN FCO JAVIER", Departamento: "11" },
  { id: 195, Codigo: "20", Valores: "SANTA MARÍA", Departamento: "11" },
  { id: 196, Codigo: "21", Valores: "STGO DE MARÍA", Departamento: "11" },
  { id: 197, Codigo: "22", Valores: "TECAPÁN", Departamento: "11" },
  { id: 198, Codigo: "23", Valores: "USULUTÁN", Departamento: "11" },
  { id: 199, Codigo: "01", Valores: "CAROLINA", Departamento: "12" },
  { id: 200, Codigo: "02", Valores: "CIUDAD BARRIOS", Departamento: "12" },
  { id: 201, Codigo: "03", Valores: "COMACARÁN", Departamento: "12" },
  { id: 202, Codigo: "04", Valores: "CHAPELTIQUE", Departamento: "12" },
  { id: 203, Codigo: "05", Valores: "CHINAMECA", Departamento: "12" },
  { id: 204, Codigo: "06", Valores: "CHIRILAGUA", Departamento: "12" },
  { id: 205, Codigo: "07", Valores: "EL TRANSITO", Departamento: "12" },
  { id: 206, Codigo: "08", Valores: "LOLOTIQUE", Departamento: "12" },
  { id: 207, Codigo: "09", Valores: "MONCAGUA", Departamento: "12" },
  { id: 208, Codigo: "10", Valores: "NUEVA GUADALUPE", Departamento: "12" },
  { id: 209, Codigo: "11", Valores: "NVO EDÉN S JUAN", Departamento: "12" },
  { id: 210, Codigo: "12", Valores: "QUELEPA", Departamento: "12" },
  { id: 211, Codigo: "13", Valores: "SAN ANT D MOSCO", Departamento: "12" },
  { id: 212, Codigo: "14", Valores: "SAN GERARDO", Departamento: "12" },
  { id: 213, Codigo: "15", Valores: "SAN JORGE", Departamento: "12" },
  { id: 214, Codigo: "16", Valores: "SAN LUIS REINA", Departamento: "12" },
  { id: 215, Codigo: "17", Valores: "SAN MIGUEL", Departamento: "12" },
  { id: 216, Codigo: "18", Valores: "SAN RAF ORIENTE", Departamento: "12" },
  { id: 217, Codigo: "19", Valores: "SESORI", Departamento: "12" },
  { id: 218, Codigo: "20", Valores: "ULUAZAPA ", Departamento: "12" },
  { id: 219, Codigo: "01", Valores: "ARAMBALA", Departamento: "13" },
  { id: 220, Codigo: "02", Valores: "CACAOPERA", Departamento: "13" },
  { id: 221, Codigo: "03", Valores: "CORINTO", Departamento: "13" },
  { id: 222, Codigo: "04", Valores: "CHILANGA", Departamento: "13" },
  { id: 223, Codigo: "05", Valores: "DELIC DE CONCEP", Departamento: "13" },
  { id: 224, Codigo: "06", Valores: "EL DIVISADERO", Departamento: "13" },
  { id: 225, Codigo: "07", Valores: "EL ROSARIO", Departamento: "13" },
  { id: 226, Codigo: "08", Valores: "GUALOCOCTI", Departamento: "13" },
  { id: 227, Codigo: "09", Valores: "GUATAJIAGUA", Departamento: "13" },
  { id: 228, Codigo: "10", Valores: "JOATECA", Departamento: "13" },
  { id: 229, Codigo: "11", Valores: "JOCOAITIQUE", Departamento: "13" },
  { id: 230, Codigo: "12", Valores: "JOCORO", Departamento: "13" },
  { id: 231, Codigo: "13", Valores: "LOLOTIQUILLO", Departamento: "13" },
  { id: 232, Codigo: "14", Valores: "MEANGUERA", Departamento: "13" },
  { id: 233, Codigo: "15", Valores: "OSICALA", Departamento: "13" },
  { id: 234, Codigo: "16", Valores: "PERQUÍN", Departamento: "13" },
  { id: 235, Codigo: "17", Valores: "SAN CARLOS", Departamento: "13" },
  { id: 236, Codigo: "18", Valores: "SAN FERNANDO", Departamento: "13" },
  { id: 237, Codigo: "19", Valores: "SAN FCO GOTERA", Departamento: "13" },
  { id: 238, Codigo: "20", Valores: "SAN ISIDRO", Departamento: "13" },
  { id: 239, Codigo: "21", Valores: "SAN SIMÓN", Departamento: "13" },
  { id: 240, Codigo: "22", Valores: "SENSEMBRA", Departamento: "13" },
  { id: 241, Codigo: "23", Valores: "SOCIEDAD", Departamento: "13" },
  { id: 242, Codigo: "24", Valores: "TOROLA", Departamento: "13" },
  { id: 243, Codigo: "25", Valores: "YAMABAL ", Departamento: "13" },
  { id: 244, Codigo: "26", Valores: "YOLOAIQUÍN ", Departamento: "13" },  
  { id: 245, Codigo: "01", Valores: "ANAMOROS", Departamento: "14" },
  { id: 246, Codigo: "02", Valores: "BOLÍVAR", Departamento: "14" },
  { id: 247, Codigo: "03", Valores: "CONCEP DE OTE", Departamento: "14" },
  { id: 248, Codigo: "04", Valores: "CONCHAGUA", Departamento: "14" },
  { id: 249, Codigo: "05", Valores: "EL CARMEN", Departamento: "14" },
  { id: 250, Codigo: "06", Valores: "EL SAUCE", Departamento: "14" },
  { id: 251, Codigo: "07", Valores: "INTIPUCÁ", Departamento: "14" },
  { id: 252, Codigo: "08", Valores: "LA UNIÓN", Departamento: "14" },
  { id: 253, Codigo: "09", Valores: "LISLIQUE", Departamento: "14" },
  { id: 254, Codigo: "10", Valores: "MEANG DEL GOLFO", Departamento: "14" },
  { id: 255, Codigo: "11", Valores: "NUEVA ESPARTA", Departamento: "14" },
  { id: 256, Codigo: "12", Valores: "PASAQUINA", Departamento: "14" },
  { id: 257, Codigo: "13", Valores: "POLORÓS", Departamento: "14" },
  { id: 258, Codigo: "14", Valores: "SAN ALEJO", Departamento: "14" },
  { id: 259, Codigo: "15", Valores: "SAN JOSE ", Departamento: "14" },
  { id: 260, Codigo: "16", Valores: "SANTA ROSA LIMA", Departamento: "14" },
  { id: 261, Codigo: "17", Valores: "YAYANTIQUE", Departamento: "14" },
  { id: 262, Codigo: "18", Valores: "YUCUAIQUÍN", Departamento: "14" },
];

//---[MEDIDAS]
const cat014 = [  
    { id: 1, Codigo: "01", Valores: "Metro" },
    { id: 2, Codigo: "02", Valores: "Yarda" },
    { id: 3, Codigo: "03", Valores: "Vara" },
    { id: 4, Codigo: "04", Valores: "Pie" },
    { id: 5, Codigo: "05", Valores: "Pulgada" },
    { id: 6, Codigo: "06", Valores: "Milímetro" },
    { id: 7, Codigo: "07", Valores: "N/A" },
    { id: 8, Codigo: "08", Valores: "Milla cuadrada" },
    { id: 9, Codigo: "09", Valores: "Kilómetro cuadrado" },
    { id: 10, Codigo: "10", Valores: "Hectárea" },
    { id: 11, Codigo: "11", Valores: "Manzana" },
    { id: 12, Codigo: "12", Valores: "Acre" },
    { id: 13, Codigo: "13", Valores: "Metro cuadrado" },
    { id: 14, Codigo: "14", Valores: "Yarda cuadrada " },
    { id: 15, Codigo: "15", Valores: "Vara cuadrada" },
    { id: 16, Codigo: "16", Valores: "Pie cuadrado" },
    { id: 17, Codigo: "17", Valores: "Pulgada cuadrada" },
    { id: 18, Codigo: "18", Valores: "Metro cúbico" },
    { id: 19, Codigo: "19", Valores: "Yarda cúbica" },
    { id: 20, Codigo: "20", Valores: "Barril" },
    { id: 21, Codigo: "21", Valores: "Pie cúbico" },
    { id: 22, Codigo: "22", Valores: "Galón" },
    { id: 23, Codigo: "23", Valores: "Litro" },
    { id: 24, Codigo: "24", Valores: "Botella" },
    { id: 25, Codigo: "25", Valores: "Pulgada cúbica" },
    { id: 26, Codigo: "26", Valores: "Mililitro" },
    { id: 27, Codigo: "27", Valores: "Onza fluida" },
    { id: 28, Codigo: "28", Valores: "N/A" },
    { id: 29, Codigo: "29", Valores: "Tonelada métrica" },
    { id: 30, Codigo: "30", Valores: "Tonelada" },
    { id: 31, Codigo: "31", Valores: "Quintal métrico " },
    { id: 32, Codigo: "32", Valores: "Quintal" },
    { id: 33, Codigo: "33", Valores: "Arroba" },
    { id: 34, Codigo: "34", Valores: "Kilogramo" },
    { id: 35, Codigo: "35", Valores: "Libra troy" },
    { id: 36, Codigo: "36", Valores: "Libra" },
    { id: 37, Codigo: "37", Valores: "Onza troy" },
    { id: 38, Codigo: "38", Valores: "Onza" },
    { id: 39, Codigo: "39", Valores: "Gramo" },
    { id: 40, Codigo: "40", Valores: "Miligramo" },
    { id: 41, Codigo: "41", Valores: "N/A" },
    { id: 42, Codigo: "42", Valores: "Megawatt" },
    { id: 43, Codigo: "43", Valores: "Kilowatt" },
    { id: 44, Codigo: "44", Valores: "Watt" },
    { id: 45, Codigo: "45", Valores: "Megavoltio-amperio" },
    { id: 46, Codigo: "46", Valores: "Kilovoltio-amperio" },
    { id: 47, Codigo: "47", Valores: "Voltio-amperio" },
    { id: 48, Codigo: "48", Valores: "N/A" },
    { id: 49, Codigo: "49", Valores: "Gigawatt-hora " },
    { id: 50, Codigo: "50", Valores: "Megawatt-hora" },
    { id: 51, Codigo: "51", Valores: "Kilowatt-hora " },
    { id: 52, Codigo: "52", Valores: "Watt-hora" },
    { id: 53, Codigo: "53", Valores: "Kilovoltio" },
    { id: 54, Codigo: "54", Valores: "Voltio" },
    { id: 55, Codigo: "55", Valores: "Millar" },
    { id: 56, Codigo: "56", Valores: "Medio millar" },
    { id: 57, Codigo: "57", Valores: "Ciento" },
    { id: 58, Codigo: "58", Valores: "Docena" },
    { id: 59, Codigo: "59", Valores: "Unidad" },
    { id: 60, Codigo: "99", Valores: "Otra" },

];

//---[TRIBUTOS]
const cat015 = [
	{id:	1	,codigo:	"20"	,valores:	"Impuesto al Valor Agregado 13%"	},	
	{id:	2	,codigo:	"C3"	,valores:	"Impuesto al Valor Agregado (exportaciones) 0%"	},	
	{id:	3	,codigo:	"59"	,valores:	"Turismo: por alojamiento (5%)"	},	
	{id:	4	,codigo:	"71"	,valores:	"Turismo: salida del país por vía aérea $7.00"	},	
	{id:	5	,codigo:	"D1"	,valores:	"FOVIAL ($0.20 Ctvs. por galón)"	},	
	{id:	6	,codigo:	"C8"	,valores:	"COTRANS ($0.10 Ctvs. por galón)"	},	
	{id:	7	,codigo:	"D5"	,valores:	"Otras tasas casos especiales"	},	
	{id:	8	,codigo:	"D4"	,valores:	"Otros impuestos casos especiales"	},	
	{id:	9	,codigo:	"A8"	,valores:	"Impuesto Especial al Combustible (0%, 0.5%, 1%)"	},	
	{id:	10	,codigo:	"57"	,valores:	"Impuesto industria de Cemento"	},	
	{id:	11	,codigo:	"90"	,valores:	"Impuesto especial a la primera matrícula"	},	
	{id:	12	,codigo:	"D4"	,valores:	"Otros impuestos casos especiales"	},	
	{id:	13	,codigo:	"D5"	,valores:	"Otras tasas casos especiales "	},	
	{id:	14	,codigo:	"A6"	,valores:	"Impuesto ad- valorem, armas de fuego, municiones explosivas y artículos similares "},	
	{id:	15	,codigo:	"C5"	,valores:	"Impuesto ad- valorem por diferencial de precios de bebidas alcohólicas (8%)"	},	
	{id:	16	,codigo:	"C6"	,valores:	"Impuesto ad- valorem por diferencial de precios al tabaco cigarrillos (39%)"	},	
	{id:	17	,codigo:	"C7"	,valores:	"Impuesto ad- valorem por diferencial de precios al tabaco cigarros (100%)"	},	
	{id:	18	,codigo:	"19"	,valores:	"Fabricante de Bebidas Gaseosas, Isotónicas, Deportivas, Fortificantes, Energizante o Estimulante"},	
	{id:	19	,codigo:	"28"	,valores:	"Importador de Bebidas Gaseosas, Isotónicas, Deportivas, Fortificantes, Energizante o Estimulante"},	
	{id:	20	,codigo:	"31"	,valores:	"Detallistas o Expendedores de Bebidas Alcohólicas"	},	
	{id:	21	,codigo:	"32"	,valores:	"Fabricante de Cerveza"	},	
	{id:	22	,codigo:	"33"	,valores:	"Importador de Cerveza"	},	
	{id:	23	,codigo:	"34"	,valores:	"Fabricante de Productos de Tabaco"	},	
	{id:	24	,codigo:	"35"	,valores:	"Importador de Productos de Tabaco"	},	
	{id:	25	,codigo:	"36"	,valores:	"Fabricante de Armas de Fuego, Municiones y Artículos Similares"	},	
	{id:	26	,codigo:	"37"	,valores:	"Importador de Arma de Fuego, Munición y Artículos. Similares"	},	
	{id:	27	,codigo:	"38"	,valores:	"Fabricante de Explosivos"	},	
	{id:	28	,codigo:	"39"	,valores:	"Importador de Explosivos "	},	
	{id:	29	,codigo:	"42"	,valores:	"Fabricante de Productos Pirotécnicos"	},	
	{id:	30	,codigo:	"43"	,valores:	"Importador de Productos Pirotécnicos"	},	
	{id:	31	,codigo:	"44"	,valores:	"Productor de Tabaco"	},	
	{id:	32	,codigo:	"50"	,valores:	"Distribuidor de Bebidas Gaseosas, Isotónicas, Deportivas, Fortificantes, Energizante o Estimulante"	},	
	{id:	33	,codigo:	"51"	,valores:	"Bebidas Alcohólicas"	},	
	{id:	34	,codigo:	"52"	,valores:	"Cerveza"	},	
	{id:	35	,codigo:	"53"	,valores:	"Productos del Tabaco"	},	
	{id:	36	,codigo:	"54"	,valores:	"Bebidas Carbonatadas o Gaseosas Simples o Endulzadas"	},	
	{id:	37	,codigo:	"55"	,valores:	"Otros Específicos"	},	
	{id:	38	,codigo:	"58"	,valores:	"Alcohol"	},	
	{id:	39	,codigo:	"77"	,valores:	"Importador de Jugos, Néctares, Bebidas con Jugo y Refrescos"	},	
	{id:	40	,codigo:	"78"	,valores:	"Distribuidor de Jugos, Néctares, Bebidas con Jugo y Refrescos"	},	
	{id:	41	,codigo:	"79"	,valores:	"Sobre Llamadas Telefónicas Provenientes del Ext"	},	
	{id:	42	,codigo:	"85"	,valores:	"Detallista de Jugos, Néctares, Bebidas con Jugo y Refrescos"	},	
	{id:	43	,codigo:	"86"	,valores:	"Fabricante de Preparaciones Concentradas o en Polvo para la Elaboración de Bebidas"},	
	{id:	44	,codigo:	"91"	,valores:	"Fabricante de Jugos, Néctares, Bebidas con Jugo y Refrescos"	},	
	{id:	45	,codigo:	"92"	,valores:	"Importador de Preparaciones Concentradas o en Polvo para la Elaboración de Bebidas"},	
	{id:	46	,codigo:	"A1"	,valores:	"Específicos y Ad-Valorem"	},	
	{id:	47	,codigo:	"A5"	,valores:	"Bebidas Gaseosas, Isotónicas, Deportivas, Fortificantes, Energizantes o Estimulantes"},	
	{id:	48	,codigo:	"A7"	,valores:	"Alcohol Etílico"	},	
	{id:	49	,codigo:	"A9"	,valores:	"Sacos Sintéticos "	},	
];

//---[CONDICIÓN DE LA OPERACIÓN]
const cat016 = [
	{ id: 1, Codigo: "1", Valores: "Contado" },
	{ id: 2, Codigo: "2", Valores: "A Crédito" },
	{ id: 3, Codigo: "3", Valores: "Otro" },
];

//---[FORMA DE PAGO]
const cat017 = [
	{ id: 1, Codigo: "01", Valores: "Billetes y monedas" },
	{ id: 2, Codigo: "02", Valores: "Tarjeta Débito" },
	{ id: 3, Codigo: "03", Valores: "Tarjeta Crédito" },
	{ id: 4, Codigo: "04", Valores: "Cheque" },
	{ id: 5, Codigo: "05", Valores: "Transferencia Depósito Bancario" },
	{ id: 6, Codigo: "06", Valores: "Vales o Cupones" },
	{ id: 7, Codigo: "08", Valores: "Dinero electrónico" },
	{ id: 8, Codigo: "09", Valores: "Monedero electrónico" },
	{ id: 9, Codigo: "10", Valores: "Certificado o tarjeta de regalo" },
	{ id: 10, Codigo: "11", Valores: "Bitcoin" },
	{ id: 11, Codigo: "12", Valores: "Otras Criptomonedas" },
	{ id: 12, Codigo: "13", Valores: "Cuentas por pagar del receptor" },
	{ id: 13, Codigo: "14", Valores: "Giro bancario" },
	{ id: 14, Codigo: "99", Valores: "Otros (se debe indicar el medio de pago)" },
];

//---[PLAZO]
const cat018 = [
	{ id: 1, Codigo: "01", Valores: "Días" },
	{ id: 2, Codigo: "02", Valores: "Meses" },
	{ id: 3, Codigo: "03", Valores: "Años" },
];

//---[ACTIVIDAD ECONOMICA]
const cat019 = [	
	{Codigo:	"01111"	,Valores:	"Cultivo de cereales excepto arroz y para forrajes"	},	
	{Codigo:	"01112"	,Valores:	"Cultivo de legumbres"	},	
	{Codigo:	"01113"	,Valores:	"Cultivo de semillas oleaginosas"	},	
	{Codigo:	"01114"	,Valores:	"Cultivo de plantas para la preparación de semillas"	},	
	{Codigo:	"01119"	,Valores:	"Cultivo de otros cereales excepto arroz y forrajeros n.c.p."	},	
	{Codigo:	"01120"	,Valores:	"Cultivo de arroz"	},	
	{Codigo:	"01131"	,Valores:	"Cultivo de raíces y tubérculos"	},	
	{Codigo:	"01132"	,Valores:	"Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares"	},	
	{Codigo:	"01133"	,Valores:	"Cultivo hortícola de fruto"	},	
	{Codigo:	"01134"	,Valores:	"Cultivo de hortalizas de hoja y otras hortalizas ncp"	},	
	{Codigo:	"01140"	,Valores:	"Cultivo de caña de azúcar"	},	
	{Codigo:	"01150"	,Valores:	"Cultivo de tabaco"	},	
	{Codigo:	"01161"	,Valores:	"Cultivo de algodón"	},	
	{Codigo:	"01162"	,Valores:	"Cultivo de fibras vegetales excepto algodón"	},	
	{Codigo:	"01191"	,Valores:	"Cultivo de plantas no perennes  para la producción de semillas y flores"	},	
	{Codigo:	"01192"	,Valores:	"Cultivo de cereales y pastos para la alimentación animal"	},	
	{Codigo:	"01199"	,Valores:	"Producción de cultivos no estacionales  ncp"	},	
	{Codigo:	"01220"	,Valores:	"Cultivo de frutas tropicales"	},	
	{Codigo:	"01230"	,Valores:	"Cultivo de cítricos"	},	
	{Codigo:	"01240"	,Valores:	"Cultivo de frutas de pepita y hueso"	},	
	{Codigo:	"01251"	,Valores:	"Cultivo de frutas ncp"	},	
	{Codigo:	"01252"	,Valores:	"Cultivo de otros frutos  y nueces de árboles y arbustos"	},	
	{Codigo:	"01260"	,Valores:	"Cultivo de frutos oleaginosos"	},	
	{Codigo:	"01271"	,Valores:	"Cultivo de café"	},	
	{Codigo:	"01272"	,Valores:	"Cultivo de plantas para la elaboración de bebidas excepto café"	},	
	{Codigo:	"01281"	,Valores:	"Cultivo de especias y aromáticas"	},	
	{Codigo:	"01282"	,Valores:	"Cultivo de plantas para la obtención de productos medicinales y farmacéuticos"	},	
	{Codigo:	"01291"	,Valores:	"Cultivo de árboles de hule (caucho) para la obtención de látex"	},	
	{Codigo:	"01292"	,Valores:	"Cultivo de plantas para la obtención de productos químicos y colorantes"	},	
	{Codigo:	"01299"	,Valores:	"Producción de cultivos perennes ncp"	},	
	{Codigo:	"01300"	,Valores:	"Propagación de plantas"	},	
	{Codigo:	"01301"	,Valores:	"Cultivo de plantas y flores ornamentales"	},	
	{Codigo:	"01410"	,Valores:	"Cría y engorde de ganado bovino"	},	
	{Codigo:	"01420"	,Valores:	"Cría de caballos y otros equinos"	},	
	{Codigo:	"01440"	,Valores:	"Cría de ovejas y cabras"	},	
	{Codigo:	"01450"	,Valores:	"Cría de cerdos"	},	
	{Codigo:	"01460"	,Valores:	"Cría de aves de corral y producción de huevos"	},	
	{Codigo:	"01491"	,Valores:	"Cría de abejas apicultura para la obtención de miel y otros productos apícolas"	},	
	{Codigo:	"01492"	,Valores:	"Cría de conejos"	},	
	{Codigo:	"01493"	,Valores:	"Cría de iguanas y garrobos"	},	
	{Codigo:	"01494"	,Valores:	"Cría de mariposas y otros insectos"	},	
	{Codigo:	"01499"	,Valores:	"Cría y obtención de productos animales n.c.p."	},	
	{Codigo:	"01500"	,Valores:	"Cultivo de productos agrícolas en combinación con la cría de animales"	},	
	{Codigo:	"01611"	,Valores:	"Servicios de maquinaria agrícola"	},	
	{Codigo:	"01612"	,Valores:	"Control de plagas"	},	
	{Codigo:	"01613"	,Valores:	"Servicios de riego"	},	
	{Codigo:	"01614"	,Valores:	"Servicios de contratación de mano de obra para la agricultura"	},	
	{Codigo:	"01619"	,Valores:	"Servicios agrícolas ncp"	},	
	{Codigo:	"01621"	,Valores:	"Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos"	},	
	{Codigo:	"01622"	,Valores:	"Servicios de mano de obra pecuaria"	},	
	{Codigo:	"01629"	,Valores:	"Servicios pecuarios ncp"	},	
	{Codigo:	"01631"	,Valores:	"Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria"	},	
	{Codigo:	"01632"	,Valores:	"Servicio de beneficio de café"	},	
	{Codigo:	"01633"	,Valores:	"Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)"	},	
	{Codigo:	"01640"	,Valores:	"Tratamiento de semillas para la propagación"	},	
	{Codigo:	"01700"	,Valores:	"Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos"	},	
	{Codigo:	"02100"	,Valores:	"Silvicultura y otras actividades forestales"	},	
	{Codigo:	"02200"	,Valores:	"Extracción de madera"	},	
	{Codigo:	"02300"	,Valores:	"Recolección de productos diferentes a la madera"	},	
	{Codigo:	"02400"	,Valores:	"Servicios de apoyo a la silvicultura"	},	
	{Codigo:	"03110"	,Valores:	"Pesca marítima de altura y costera"	},	
	{Codigo:	"03120"	,Valores:	"Pesca de agua dulce"	},	
	{Codigo:	"03210"	,Valores:	"Acuicultura marítima"	},	
	{Codigo:	"03220"	,Valores:	"Acuicultura de agua dulce"	},	
	{Codigo:	"03300"	,Valores:	"Servicios de apoyo a la pesca y acuicultura"	},	
	{Codigo:	"05100"	,Valores:	"Extracción de hulla"	},	
	{Codigo:	"05200"	,Valores:	"Extracción y aglomeración de lignito"	},	
	{Codigo:	"06100"	,Valores:	"Extracción de petróleo crudo"	},	
	{Codigo:	"06200"	,Valores:	"Extracción de gas natural"	},	
	{Codigo:	"07100"	,Valores:	"Extracción de minerales  de hierro"	},	
	{Codigo:	"07210"	,Valores:	"Extracción de minerales de uranio y torio"	},	
	{Codigo:	"07290"	,Valores:	"Extracción de minerales metalíferos no ferrosos"	},	
	{Codigo:	"08100"	,Valores:	"Extracción de piedra, arena y arcilla"	},	
	{Codigo:	"08910"	,Valores:	"Extracción de minerales para la fabricación de abonos y productos químicos"	},	
	{Codigo:	"08920"	,Valores:	"Extracción y aglomeración de turba"	},	
	{Codigo:	"08930"	,Valores:	"Extracción de sal"	},	
	{Codigo:	"08990"	,Valores:	"Explotación de otras minas y canteras ncp"	},	
	{Codigo:	"09100"	,Valores:	"Actividades de apoyo a la extracción de petróleo y gas natural"	},	
	{Codigo:	"09900"	,Valores:	"Actividades de apoyo a la explotación de minas y canteras"	},	
	{Codigo:	"10101"	,Valores:	"Servicio de rastros y mataderos de bovinos y porcinos"	},	
	{Codigo:	"10102"	,Valores:	"Matanza y procesamiento de bovinos y porcinos"	},	
	{Codigo:	"10103"	,Valores:	"Matanza y procesamientos de aves de corral"	},	
	{Codigo:	"10104"	,Valores:	"Elaboración y conservación de embutidos y tripas naturales"	},	
	{Codigo:	"10105"	,Valores:	"Servicios de conservación y empaque de carnes"	},	
	{Codigo:	"10106"	,Valores:	"Elaboración y conservación de grasas y aceites animales"	},	
	{Codigo:	"10107"	,Valores:	"Servicios de molienda de carne"	},	
	{Codigo:	"10108"	,Valores:	"Elaboración de productos de carne ncp"	},	
	{Codigo:	"10201"	,Valores:	"Procesamiento y conservación de pescado, crustáceos y moluscos"	},	
	{Codigo:	"10209"	,Valores:	"Fabricación de productos de pescado ncp"	},	
	{Codigo:	"10301"	,Valores:	"Elaboración de jugos de frutas y hortalizas"	},	
	{Codigo:	"10302"	,Valores:	"Elaboración y envase de jaleas, mermeladas y frutas deshidratadas"	},	
	{Codigo:	"10309"	,Valores:	"Elaboración de productos de frutas y hortalizas n.c.p."	},	
	{Codigo:	"10401"	,Valores:	"Fabricación de aceites y grasas vegetales y animales comestibles"	},	
	{Codigo:	"10402"	,Valores:	"Fabricación de aceites y grasas vegetales y animales no comestibles"	},	
	{Codigo:	"10409"	,Valores:	"Servicio de maquilado de aceites"	},	
	{Codigo:	"10501"	,Valores:	"Fabricación de productos lácteos excepto sorbetes y quesos sustitutos"	},	
	{Codigo:	"10502"	,Valores:	"Fabricación de sorbetes y helados"	},	
	{Codigo:	"10503"	,Valores:	"Fabricación de quesos"	},	
	{Codigo:	"10611"	,Valores:	"Molienda de cereales"	},	
	{Codigo:	"10612"	,Valores:	"Elaboración de cereales para el desayuno y similares"	},	
	{Codigo:	"10613"	,Valores:	"Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072  y beneficio de café rama 0163)"	},	
	{Codigo:	"10621"	,Valores:	"Fabricación de almidón"	},	
	{Codigo:	"10628"	,Valores:	"Servicio de molienda de maíz húmedo molino para nixtamal"	},	
	{Codigo:	"10711"	,Valores:	"Elaboración de tortillas"	},	
	{Codigo:	"10712"	,Valores:	"Fabricación de pan, galletas y barquillos"	},	
	{Codigo:	"10713"	,Valores:	"Fabricación de repostería"	},	
	{Codigo:	"10721"	,Valores:	"Ingenios azucareros"	},	
	{Codigo:	"10722"	,Valores:	"Molienda de caña de azúcar para la elaboración de dulces"	},	
	{Codigo:	"10723"	,Valores:	"Elaboración de jarabes de azúcar y otros similares"	},	
	{Codigo:	"10724"	,Valores:	"Maquilado de azúcar de caña"	},	
	{Codigo:	"10730"	,Valores:	"Fabricación de cacao, chocolates y  productos de confitería"	},	
	{Codigo:	"10740"	,Valores:	"Elaboración de macarrones, fideos, y productos farináceos similares"	},	
	{Codigo:	"10750"	,Valores:	"Elaboración de comidas y platos preparados para la reventa en locales y/o  para exportación"	},	
	{Codigo:	"10791"	,Valores:	"Elaboración de productos de café"	},	
	{Codigo:	"10792"	,Valores:	"Elaboración de especies, sazonadores y condimentos"	},	
	{Codigo:	"10793"	,Valores:	"Elaboración de sopas, cremas y consomé"	},	
	{Codigo:	"10794"	,Valores:	"Fabricación de bocadillos tostados y/o fritos"	},	
	{Codigo:	"10799"	,Valores:	"Elaboración de productos alimenticios ncp"	},	
	{Codigo:	"10800"	,Valores:	"Elaboración de alimentos preparados para animales"	},	
	{Codigo:	"11012"	,Valores:	"Fabricación de aguardiente y licores"	},	
	{Codigo:	"11020"	,Valores:	"Elaboración de vinos"	},	
	{Codigo:	"11030"	,Valores:	"Fabricación de cerveza"	},	
	{Codigo:	"11041"	,Valores:	"Fabricación de aguas gaseosas"	},	
	{Codigo:	"11042"	,Valores:	"Fabricación y envasado  de agua"	},	
	{Codigo:	"11043"	,Valores:	"Elaboración de refrescos"	},	
	{Codigo:	"11048"	,Valores:	"Maquilado de aguas gaseosas"	},	
	{Codigo:	"11049"	,Valores:	"Elaboración de bebidas no alcohólicas"	},	
	{Codigo:	"12000"	,Valores:	"Elaboración de productos de tabaco"	},	
	{Codigo:	"13111"	,Valores:	"Preparación de fibras textiles"	},	
	{Codigo:	"13112"	,Valores:	"Fabricación de hilados"	},	
	{Codigo:	"13120"	,Valores:	"Fabricación de telas"	},	
	{Codigo:	"13130"	,Valores:	"Acabado de productos textiles"	},	
	{Codigo:	"13910"	,Valores:	"Fabricación de tejidos de punto y  ganchillo"	},	
	{Codigo:	"13921"	,Valores:	"Fabricación de productos textiles para el hogar"	},	
	{Codigo:	"13922"	,Valores:	"Sacos, bolsas y otros artículos textiles"	},	
	{Codigo:	"13929"	,Valores:	"Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir n.c.p"	},	
	{Codigo:	"13930"	,Valores:	"Fabricación de tapices y alfombras"	},	
	{Codigo:	"13941"	,Valores:	"Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)"	},	
	{Codigo:	"13942"	,Valores:	"Fabricación de redes de diversos materiales"	},	
	{Codigo:	"13948"	,Valores:	"Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)"	},	
	{Codigo:	"13991"	,Valores:	"Fabricación de adornos, etiquetas y otros artículos para prendas de vestir"	},	
	{Codigo:	"13992"	,Valores:	"Servicio de bordados en artículos y prendas de tela"	},	
	{Codigo:	"13999"	,Valores:	"Fabricación de productos textiles ncp"	},	
	{Codigo:	"14101"	,Valores:	"Fabricación de ropa  interior, para dormir y similares"	},	
	{Codigo:	"14102"	,Valores:	"Fabricación de ropa para niños"	},	
	{Codigo:	"14103"	,Valores:	"Fabricación de prendas de vestir para ambos sexos"	},	
	{Codigo:	"14104"	,Valores:	"Confección de prendas a medida"	},	
	{Codigo:	"14105"	,Valores:	"Fabricación de prendas de vestir para deportes"	},	
	{Codigo:	"14106"	,Valores:	"Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles"	},	
	{Codigo:	"14108"	,Valores:	"Maquilado  de prendas de vestir, accesorios y otros"	},	
	{Codigo:	"14109"	,Valores:	"Fabricación de prendas y accesorios de vestir n.c.p."	},	
	{Codigo:	"14200"	,Valores:	"Fabricación de artículos de piel"	},	
	{Codigo:	"14301"	,Valores:	"Fabricación de calcetines, calcetas, medias (panty house) y otros similares"	},	
	{Codigo:	"14302"	,Valores:	"Fabricación de ropa interior de tejido de punto"	},	
	{Codigo:	"14309"	,Valores:	"Fabricación de prendas de vestir de tejido de punto ncp"	},	
	{Codigo:	"15110"	,Valores:	"Curtido y adobo de cueros; adobo y teñido de pieles"	},	
	{Codigo:	"15121"	,Valores:	"Fabricación de maletas, bolsos de mano y otros artículos de marroquinería"	},	
	{Codigo:	"15122"	,Valores:	"Fabricación de monturas, accesorios y vainas  talabartería"	},	
	{Codigo:	"15123"	,Valores:	"Fabricación  de artesanías principalmente de cuero natural y sintético"	},	
	{Codigo:	"15128"	,Valores:	"Maquilado de artículos de cuero natural, sintético y de otros materiales"	},	
	{Codigo:	"15201"	,Valores:	"Fabricación de calzado"	},	
	{Codigo:	"15202"	,Valores:	"Fabricación de partes y accesorios de calzado"	},	
	{Codigo:	"15208"	,Valores:	"Maquilado de partes y accesorios de calzado"	},	
	{Codigo:	"16100"	,Valores:	"Aserradero y acepilladura de madera"	},	
	{Codigo:	"16210"	,Valores:	"Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción"	},	
	{Codigo:	"16220"	,Valores:	"Fabricación de partes y piezas de carpintería para edificios y construcciones"	},	
	{Codigo:	"16230"	,Valores:	"Fabricación de envases y recipientes de madera"	},	
	{Codigo:	"16292"	,Valores:	"Fabricación de artesanías de madera, semillas,  materiales trenzables"	},	
	{Codigo:	"16299"	,Valores:	"Fabricación de productos de madera, corcho, paja y materiales trenzables ncp"	},	
	{Codigo:	"17010"	,Valores:	"Fabricación de pasta de madera, papel y cartón"	},	
	{Codigo:	"17020"	,Valores:	"Fabricación de papel y cartón ondulado y envases de papel y cartón"	},	
	{Codigo:	"17091"	,Valores:	"Fabricación de artículos de papel y cartón de uso personal y doméstico"	},	
	{Codigo:	"17092"	,Valores:	"Fabricación de productos de papel ncp"	},	
	{Codigo:	"18110"	,Valores:	"Impresión"	},	
	{Codigo:	"18120"	,Valores:	"Servicios relacionados con la impresión"	},	
	{Codigo:	"18200"	,Valores:	"Reproducción de grabaciones"	},	
	{Codigo:	"19100"	,Valores:	"Fabricación de productos de hornos de coque"	},	
	{Codigo:	"19201"	,Valores:	"Fabricación de combustible"	},	
	{Codigo:	"19202"	,Valores:	"Fabricación de aceites y lubricantes"	},	
	{Codigo:	"20111"	,Valores:	"Fabricación de materias primas para la fabricación de colorantes"	},	
	{Codigo:	"20112"	,Valores:	"Fabricación de materiales curtientes"	},	
	{Codigo:	"20113"	,Valores:	"Fabricación de gases industriales"	},	
	{Codigo:	"20114"	,Valores:	"Fabricación de alcohol etílico"	},	
	{Codigo:	"20119"	,Valores:	"Fabricación de sustancias químicas básicas"	},	
	{Codigo:	"20120"	,Valores:	"Fabricación de abonos y fertilizantes"	},	
	{Codigo:	"20130"	,Valores:	"Fabricación de plástico y caucho en formas primarias"	},	
	{Codigo:	"20210"	,Valores:	"Fabricación de plaguicidas y otros productos químicos de uso agropecuario"	},	
	{Codigo:	"20220"	,Valores:	"Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas"	},	
	{Codigo:	"20231"	,Valores:	"Fabricación de jabones, detergentes y similares para limpieza"	},	
	{Codigo:	"20232"	,Valores:	"Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc."	},	
	{Codigo:	"20291"	,Valores:	"Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras"	},	
	{Codigo:	"20292"	,Valores:	"Fabricación de productos pirotécnicos, explosivos y municiones"	},	
	{Codigo:	"20299"	,Valores:	"Fabricación de productos químicos n.c.p."	},	
	{Codigo:	"20300"	,Valores:	"Fabricación de fibras artificiales"	},	
	{Codigo:	"21001"	,Valores:	"Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos"	},	
	{Codigo:	"21008"	,Valores:	"Maquilado de medicamentos"	},	
	{Codigo:	"22110"	,Valores:	"Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas"	},	
	{Codigo:	"22190"	,Valores:	"Fabricación de otros productos de caucho"	},	
	{Codigo:	"22201"	,Valores:	"Fabricación de envases plásticos"	},	
	{Codigo:	"22202"	,Valores:	"Fabricación de productos plásticos para uso personal o doméstico"	},	
	{Codigo:	"22208"	,Valores:	"Maquila de plásticos"	},	
	{Codigo:	"22209"	,Valores:	"Fabricación de productos plásticos n.c.p."	},	
	{Codigo:	"23101"	,Valores:	"Fabricación de vidrio"	},	
	{Codigo:	"23102"	,Valores:	"Fabricación de recipientes y envases de vidrio"	},	
	{Codigo:	"23108"	,Valores:	"Servicio de maquilado"	},	
	{Codigo:	"23109"	,Valores:	"Fabricación de productos de vidrio ncp"	},	
	{Codigo:	"23910"	,Valores:	"Fabricación de productos refractarios"	},	
	{Codigo:	"23920"	,Valores:	"Fabricación de productos de arcilla para la construcción"	},	
	{Codigo:	"23931"	,Valores:	"Fabricación de productos de cerámica y porcelana no refractaria"	},	
	{Codigo:	"23932"	,Valores:	"Fabricación de productos de cerámica y porcelana ncp"	},	
	{Codigo:	"23940"	,Valores:	"Fabricación de cemento, cal y yeso"	},	
	{Codigo:	"23950"	,Valores:	"Fabricación de artículos de hormigón, cemento y yeso"	},	
	{Codigo:	"23960"	,Valores:	"Corte, tallado y acabado de la piedra"	},	
	{Codigo:	"23990"	,Valores:	"Fabricación de productos minerales no metálicos ncp"	},	
	{Codigo:	"24100"	,Valores:	"Industrias básicas de hierro y acero"	},	
	{Codigo:	"24200"	,Valores:	"Fabricación de productos primarios de metales preciosos y metales no ferrosos"	},	
	{Codigo:	"24310"	,Valores:	"Fundición de hierro y acero"	},	
	{Codigo:	"24320"	,Valores:	"Fundición de metales no ferrosos"	},	
	{Codigo:	"25111"	,Valores:	"Fabricación de productos metálicos para uso estructural"	},	
	{Codigo:	"25118"	,Valores:	"Servicio de maquila para la fabricación de estructuras metálicas"	},	
	{Codigo:	"25120"	,Valores:	"Fabricación de tanques, depósitos y recipientes de metal"	},	
	{Codigo:	"25130"	,Valores:	"Fabricación de generadores de vapor, excepto calderas de agua caliente  para calefacción central"	},	
	{Codigo:	"25200"	,Valores:	"Fabricación de armas y municiones"	},	
	{Codigo:	"25910"	,Valores:	"Forjado, prensado, estampado y laminado de metales; pulvimetalurgia"	},	
	{Codigo:	"25920"	,Valores:	"Tratamiento y revestimiento de metales"	},	
	{Codigo:	"25930"	,Valores:	"Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería"	},	
	{Codigo:	"25991"	,Valores:	"Fabricación de envases y artículos conexos de metal"	},	
	{Codigo:	"25992"	,Valores:	"Fabricación de artículos metálicos de uso personal y/o doméstico"	},	
	{Codigo:	"25999"	,Valores:	"Fabricación de productos elaborados de metal ncp"	},	
	{Codigo:	"26100"	,Valores:	"Fabricación de componentes electrónicos"	},	
	{Codigo:	"26200"	,Valores:	"Fabricación de computadoras y equipo conexo"	},	
	{Codigo:	"26300"	,Valores:	"Fabricación de equipo de comunicaciones"	},	
	{Codigo:	"26400"	,Valores:	"Fabricación de aparatos  electrónicos de consumo para audio, video radio y televisión"	},	
	{Codigo:	"26510"	,Valores:	"Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales"	},	
	{Codigo:	"26520"	,Valores:	"Fabricación de relojes y piezas de relojes"	},	
	{Codigo:	"26600"	,Valores:	"Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico"	},	
	{Codigo:	"26700"	,Valores:	"Fabricación de instrumentos de óptica y equipo fotográfico"	},	
	{Codigo:	"26800"	,Valores:	"Fabricación de medios magnéticos y ópticos"	},	
	{Codigo:	"27100"	,Valores:	"Fabricación de motores, generadores , transformadores eléctricos, aparatos de distribución y control de electricidad"	},	
	{Codigo:	"27200"	,Valores:	"Fabricación de pilas, baterías y acumuladores"	},	
	{Codigo:	"27310"	,Valores:	"Fabricación de cables de fibra óptica"	},	
	{Codigo:	"27320"	,Valores:	"Fabricación de otros  hilos y cables eléctricos"	},	
	{Codigo:	"27330"	,Valores:	"Fabricación de dispositivos de cableados"	},	
	{Codigo:	"27400"	,Valores:	"Fabricación de equipo eléctrico de iluminación"	},	
	{Codigo:	"27500"	,Valores:	"Fabricación de aparatos de uso doméstico"	},	
	{Codigo:	"27900"	,Valores:	"Fabricación de otros tipos de equipo eléctrico"	},	
	{Codigo:	"28110"	,Valores:	"Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas"	},	
	{Codigo:	"28120"	,Valores:	"Fabricación de equipo hidráulico"	},	
	{Codigo:	"28130"	,Valores:	"Fabricación de otras bombas, compresores, grifos y válvulas"	},	
	{Codigo:	"28140"	,Valores:	"Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión"	},	
	{Codigo:	"28150"	,Valores:	"Fabricación de hornos y quemadores"	},	
	{Codigo:	"28160"	,Valores:	"Fabricación de equipo de elevación y manipulación"	},	
	{Codigo:	"28170"	,Valores:	"Fabricación de maquinaria y equipo de oficina"	},	
	{Codigo:	"28180"	,Valores:	"Fabricación de herramientas manuales"	},	
	{Codigo:	"28190"	,Valores:	"Fabricación de otros tipos de maquinaria de uso general"	},	
	{Codigo:	"28210"	,Valores:	"Fabricación de maquinaria agropecuaria y forestal"	},	
	{Codigo:	"28220"	,Valores:	"Fabricación de máquinas para conformar metales y maquinaria herramienta"	},	
	{Codigo:	"28230"	,Valores:	"Fabricación de maquinaria metalúrgica"	},	
	{Codigo:	"28240"	,Valores:	"Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción"	},	
	{Codigo:	"28250"	,Valores:	"Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco"	},	
	{Codigo:	"28260"	,Valores:	"Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros"	},	
	{Codigo:	"28291"	,Valores:	"Fabricación de máquinas para imprenta"	},	
	{Codigo:	"28299"	,Valores:	"Fabricación de maquinaria de uso especial ncp"	},	
	{Codigo:	"29100"	,Valores:	"Fabricación vehículos automotores"	},	
	{Codigo:	"29200"	,Valores:	"Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques"	},	
	{Codigo:	"29300"	,Valores:	"Fabricación de partes, piezas y accesorios para vehículos automotores"	},	
	{Codigo:	"30110"	,Valores:	"Fabricación de buques"	},	
	{Codigo:	"30120"	,Valores:	"Construcción y reparación de embarcaciones de recreo"	},	
	{Codigo:	"30200"	,Valores:	"Fabricación de locomotoras y de material rodante"	},	
	{Codigo:	"30300"	,Valores:	"Fabricación de aeronaves y naves espaciales"	},	
	{Codigo:	"30400"	,Valores:	"Fabricación de vehículos militares de combate"	},	
	{Codigo:	"30910"	,Valores:	"Fabricación de motocicletas"	},	
	{Codigo:	"30920"	,Valores:	"Fabricación de bicicletas y sillones de ruedas para inválidos"	},	
	{Codigo:	"30990"	,Valores:	"Fabricación de equipo de transporte ncp"	},	
	{Codigo:	"31001"	,Valores:	"Fabricación de colchones y somier"	},	
	{Codigo:	"31002"	,Valores:	"Fabricación de muebles y otros productos de madera a medida"	},	
	{Codigo:	"31008"	,Valores:	"Servicios de maquilado de muebles"	},	
	{Codigo:	"31009"	,Valores:	"Fabricación de muebles ncp"	},	
	{Codigo:	"32110"	,Valores:	"Fabricación de joyas platerías y joyerías"	},	
	{Codigo:	"32120"	,Valores:	"Fabricación de joyas de imitación (fantasía) y artículos conexos"	},	
	{Codigo:	"32200"	,Valores:	"Fabricación de instrumentos musicales"	},	
	{Codigo:	"32301"	,Valores:	"Fabricación de artículos de deporte"	},	
	{Codigo:	"32308"	,Valores:	"Servicio de maquila de productos deportivos"	},	
	{Codigo:	"32401"	,Valores:	"Fabricación de juegos de mesa y de salón"	},	
	{Codigo:	"32402"	,Valores:	"Servicio de maquilado de juguetes y juegos"	},	
	{Codigo:	"32409"	,Valores:	"Fabricación de juegos y juguetes n.c.p."	},	
	{Codigo:	"32500"	,Valores:	"Fabricación de instrumentos y materiales médicos y odontológicos"	},	
	{Codigo:	"32901"	,Valores:	"Fabricación de lápices, bolígrafos, sellos y artículos de librería en general"	},	
	{Codigo:	"32902"	,Valores:	"Fabricación de escobas, cepillos, pinceles y similares"	},	
	{Codigo:	"32903"	,Valores:	"Fabricación de artesanías de materiales diversos"	},	
	{Codigo:	"32904"	,Valores:	"Fabricación de artículos de uso personal y domésticos n.c.p."	},	
	{Codigo:	"32905"	,Valores:	"Fabricación de accesorios para las confecciones y la marroquinería n.c.p."	},	
	{Codigo:	"32908"	,Valores:	"Servicios de maquila ncp"	},	
	{Codigo:	"32909"	,Valores:	"Fabricación de productos manufacturados n.c.p."	},	
	{Codigo:	"33110"	,Valores:	"Reparación y mantenimiento de productos elaborados de metal"	},	
	{Codigo:	"33120"	,Valores:	"Reparación y mantenimiento de maquinaria"	},	
	{Codigo:	"33130"	,Valores:	"Reparación y mantenimiento de equipo electrónico y óptico"	},	
	{Codigo:	"33140"	,Valores:	"Reparación y mantenimiento  de equipo eléctrico"	},	
	{Codigo:	"33150"	,Valores:	"Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores"	},	
	{Codigo:	"33190"	,Valores:	"Reparación y mantenimiento de equipos n.c.p."	},	
	{Codigo:	"33200"	,Valores:	"Instalación de maquinaria y equipo industrial"	},	
	{Codigo:	"35101"	,Valores:	"Generación de energía eléctrica"	},	
	{Codigo:	"35102"	,Valores:	"Transmisión de energía eléctrica"	},	
	{Codigo:	"35103"	,Valores:	"Distribución de energía eléctrica"	},	
	{Codigo:	"35200"	,Valores:	"Fabricación de gas, distribución de combustibles gaseosos por tuberías"	},	
	{Codigo:	"35300"	,Valores:	"Suministro de vapor y agua caliente"	},	
	{Codigo:	"36000"	,Valores:	"Captación, tratamiento y suministro de agua"	},	
	{Codigo:	"37000"	,Valores:	"Evacuación de aguas residuales (alcantarillado)"	},	
	{Codigo:	"38110"	,Valores:	"Recolección y transporte de desechos sólidos proveniente de hogares y  sector urbano"	},	
	{Codigo:	"38120"	,Valores:	"Recolección de desechos peligrosos"	},	
	{Codigo:	"38210"	,Valores:	"Tratamiento y eliminación de desechos inicuos"	},	
	{Codigo:	"38220"	,Valores:	"Tratamiento y eliminación de desechos peligrosos"	},	
	{Codigo:	"38301"	,Valores:	"Reciclaje de desperdicios y desechos textiles"	},	
	{Codigo:	"38302"	,Valores:	"Reciclaje de desperdicios y desechos de plástico y caucho"	},	
	{Codigo:	"38303"	,Valores:	"Reciclaje de desperdicios y desechos de vidrio"	},	
	{Codigo:	"38304"	,Valores:	"Reciclaje de desperdicios y desechos de papel y cartón"	},	
	{Codigo:	"38305"	,Valores:	"Reciclaje de desperdicios y desechos metálicos"	},	
	{Codigo:	"38309"	,Valores:	"Reciclaje de desperdicios y desechos no metálicos  n.c.p."	},	
	{Codigo:	"39000"	,Valores:	"Actividades de Saneamiento y otros Servicios de Gestión de Desechos"	},	
	{Codigo:	"41001"	,Valores:	"Construcción de edificios residenciales"	},	
	{Codigo:	"41002"	,Valores:	"Construcción de edificios no residenciales"	},	
	{Codigo:	"42100"	,Valores:	"Construcción de carreteras, calles y caminos"	},	
	{Codigo:	"42200"	,Valores:	"Construcción de proyectos de servicio público"	},	
	{Codigo:	"42900"	,Valores:	"Construcción de obras de ingeniería civil n.c.p."	},	
	{Codigo:	"43110"	,Valores:	"Demolición"	},	
	{Codigo:	"43120"	,Valores:	"Preparación de terreno"	},	
	{Codigo:	"43210"	,Valores:	"Instalaciones eléctricas"	},	
	{Codigo:	"43220"	,Valores:	"Instalación de fontanería, calefacción y aire acondicionado"	},	
	{Codigo:	"43290"	,Valores:	"Otras instalaciones para obras de construcción"	},	
	{Codigo:	"43300"	,Valores:	"Terminación y acabado de edificios"	},	
	{Codigo:	"43900"	,Valores:	"Otras actividades especializadas de construcción"	},	
	{Codigo:	"43901"	,Valores:	"Fabricación de techos y materiales diversos"	},	
	{Codigo:	"45100"	,Valores:	"Venta de vehículos automotores"	},	
	{Codigo:	"45201"	,Valores:	"Reparación mecánica de vehículos automotores"	},	
	{Codigo:	"45202"	,Valores:	"Reparaciones eléctricas del automotor y recarga de baterías"	},	
	{Codigo:	"45203"	,Valores:	"Enderezado y pintura de vehículos automotores"	},	
	{Codigo:	"45204"	,Valores:	"Reparaciones de radiadores, escapes y silenciadores"	},	
	{Codigo:	"45205"	,Valores:	"Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio"	},	
	{Codigo:	"45206"	,Valores:	"Reparación de llantas de vehículos automotores"	},	
	{Codigo:	"45207"	,Valores:	"Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)"	},	
	{Codigo:	"45208"	,Valores:	"Lavado y pasteado de vehículos (carwash)"	},	
	{Codigo:	"45209"	,Valores:	"Reparaciones de vehículos n.c.p."	},	
	{Codigo:	"45211"	,Valores:	"Remolque de vehículos automotores"	},	
	{Codigo:	"45301"	,Valores:	"Venta de partes, piezas y accesorios nuevos para vehículos automotores"	},	
	{Codigo:	"45302"	,Valores:	"Venta de partes, piezas y accesorios usados para vehículos automotores"	},	
	{Codigo:	"45401"	,Valores:	"Venta de motocicletas"	},	
	{Codigo:	"45402"	,Valores:	"Venta de repuestos, piezas y accesorios de motocicletas"	},	
	{Codigo:	"45403"	,Valores:	"Mantenimiento y reparación  de motocicletas"	},	
	{Codigo:	"46100"	,Valores:	"Venta al por mayor a cambio de retribución o por contrata"	},	
	{Codigo:	"46201"	,Valores:	"Venta al por mayor de materias primas agrícolas"	},	
	{Codigo:	"46202"	,Valores:	"Venta al por mayor de productos de la silvicultura"	},	
	{Codigo:	"46203"	,Valores:	"Venta al por mayor de productos pecuarios y de granja"	},	
	{Codigo:	"46211"	,Valores:	"Venta de productos para uso agropecuario"	},	
	{Codigo:	"46291"	,Valores:	"Venta al por mayor de granos básicos (cereales, leguminosas)"	},	
	{Codigo:	"46292"	,Valores:	"Venta  al por mayor de semillas mejoradas para cultivo"	},	
	{Codigo:	"46293"	,Valores:	"Venta  al por mayor de café oro y uva"	},	
	{Codigo:	"46294"	,Valores:	"Venta  al por mayor de caña de azúcar"	},	
	{Codigo:	"46295"	,Valores:	"Venta al por mayor de flores, plantas  y otros productos naturales"	},	
	{Codigo:	"46296"	,Valores:	"Venta al por mayor de productos agrícolas"	},	
	{Codigo:	"46297"	,Valores:	"Venta  al por mayor de ganado bovino (vivo)"	},	
	{Codigo:	"46298"	,Valores:	"Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos"	},	
	{Codigo:	"46299"	,Valores:	"Venta de otras especies vivas del reino animal"	},	
	{Codigo:	"46301"	,Valores:	"Venta al por mayor de alimentos"	},	
	{Codigo:	"46302"	,Valores:	"Venta al por mayor de bebidas"	},	
	{Codigo:	"46303"	,Valores:	"Venta al por mayor de tabaco"	},	
	{Codigo:	"46371"	,Valores:	"Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos"	},	
	{Codigo:	"46372"	,Valores:	"Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves"	},	
	{Codigo:	"46373"	,Valores:	"Venta al por mayor de carne bovina y porcina, productos de carne y embutidos"	},	
	{Codigo:	"46374"	,Valores:	"Venta  al por mayor de huevos"	},	
	{Codigo:	"46375"	,Valores:	"Venta al por mayor de productos lácteos"	},	
	{Codigo:	"46376"	,Valores:	"Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, respostería, etc.)"	},	
	{Codigo:	"46377"	,Valores:	"Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal"	},	
	{Codigo:	"46378"	,Valores:	"Venta al por mayor de sal comestible"	},	
	{Codigo:	"46379"	,Valores:	"Venta al por mayor de azúcar"	},	
	{Codigo:	"46391"	,Valores:	"Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.)"	},	
	{Codigo:	"46392"	,Valores:	"Venta al por mayor de aguas gaseosas"	},	
	{Codigo:	"46393"	,Valores:	"Venta al por mayor de agua purificada"	},	
	{Codigo:	"46394"	,Valores:	"Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo"	},	
	{Codigo:	"46395"	,Valores:	"Venta al por mayor de cerveza y licores"	},	
	{Codigo:	"46396"	,Valores:	"Venta al por mayor de hielo"	},	
	{Codigo:	"46411"	,Valores:	"Venta al por mayor de hilados, tejidos y productos textiles de mercería"	},	
	{Codigo:	"46412"	,Valores:	"Venta al por mayor de artículos textiles excepto confecciones para el hogar"	},	
	{Codigo:	"46413"	,Valores:	"Venta al por mayor de confecciones textiles para el hogar"	},	
	{Codigo:	"46414"	,Valores:	"Venta al por mayor de prendas de vestir y accesorios de vestir"	},	
	{Codigo:	"46415"	,Valores:	"Venta al por mayor de ropa usada"	},	
	{Codigo:	"46416"	,Valores:	"Venta al por mayor de calzado"	},	
	{Codigo:	"46417"	,Valores:	"Venta al por mayor de artículos de marroquinería y talabartería"	},	
	{Codigo:	"46418"	,Valores:	"Venta al por mayor de artículos de peletería"	},	
	{Codigo:	"46419"	,Valores:	"Venta al por mayor de otros artículos textiles n.c.p."	},	
	{Codigo:	"46471"	,Valores:	"Venta al por mayor de instrumentos musicales"	},	
	{Codigo:	"46472"	,Valores:	"Venta al por mayor de colchones, almohadas, cojines, etc."	},	
	{Codigo:	"46473"	,Valores:	"Venta al por mayor de artículos de aluminio para el hogar y para otros usos"	},	
	{Codigo:	"46474"	,Valores:	"Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax  y no desechables"	},	
	{Codigo:	"46475"	,Valores:	"Venta al por mayor de cámaras fotográficas, accesorios y materiales"	},	
	{Codigo:	"46482"	,Valores:	"Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario"	},	
	{Codigo:	"46483"	,Valores:	"Venta al por mayor de productos y artículos de belleza  y de  uso personal"	},	
	{Codigo:	"46484"	,Valores:	"Venta de productos farmacéuticos y medicinales"	},	
	{Codigo:	"46491"	,Valores:	"Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza"	},	
	{Codigo:	"46492"	,Valores:	"Venta al por mayor de relojes y artículos de joyería"	},	
	{Codigo:	"46493"	,Valores:	"Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar;  artículos de iluminación"	},	
	{Codigo:	"46494"	,Valores:	"Venta al por mayor de artículos de bazar y similares"	},	
	{Codigo:	"46495"	,Valores:	"Venta al por mayor de artículos de óptica"	},	
	{Codigo:	"46496"	,Valores:	"Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general"	},	
	{Codigo:	"46497"	,Valores:	"Venta de artículos deportivos, juguetes y rodados"	},	
	{Codigo:	"46498"	,Valores:	"Venta al por mayor de productos usados para el hogar o el uso personal"	},	
	{Codigo:	"46499"	,Valores:	"Venta al por mayor de enseres domésticos y de uso personal n.c.p."	},	
	{Codigo:	"46500"	,Valores:	"Venta al por mayor de bicicletas, partes, accesorios y otros"	},	
	{Codigo:	"46510"	,Valores:	"Venta al por mayor de computadoras, equipo periférico y programas informáticos"	},	
	{Codigo:	"46520"	,Valores:	"Venta al por mayor de equipos de comunicación"	},	
	{Codigo:	"46530"	,Valores:	"Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros"	},	
	{Codigo:	"46590"	,Valores:	"Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control"	},	
	{Codigo:	"46591"	,Valores:	"Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y  sus  productos"	},	
	{Codigo:	"46592"	,Valores:	"Venta al por mayor de maquinaria,  equipo, accesorios y materiales para las industria gráfica y del papel, cartón y productos de papel y cartón"	},	
	{Codigo:	"46593"	,Valores:	"Venta al por mayor de maquinaria, equipo, accesorios y materiales para la  industria de  productos químicos, plástico y caucho"	},	
	{Codigo:	"46594"	,Valores:	"Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos"	},	
	{Codigo:	"46595"	,Valores:	"Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos"	},	
	{Codigo:	"46596"	,Valores:	"Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación"	},	
	{Codigo:	"46597"	,Valores:	"Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero"	},	
	{Codigo:	"46598"	,Valores:	"Venta al por mayor de maquinaria, equipo y accesorios para la construcción y explotación de minas y canteras"	},	
	{Codigo:	"46599"	,Valores:	"Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes"	},	
	{Codigo:	"46610"	,Valores:	"Venta al por mayor  de otros combustibles sólidos, líquidos, gaseosos y de productos conexos"	},	
	{Codigo:	"46612"	,Valores:	"Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria  y otros"	},	
	{Codigo:	"46613"	,Valores:	"Venta al por mayor de lubricantes, grasas y  otros aceites para automotores, maquinaria  industrial, etc."	},	
	{Codigo:	"46614"	,Valores:	"Venta al por mayor de gas propano"	},	
	{Codigo:	"46615"	,Valores:	"Venta al  por mayor de leña y carbón"	},	
	{Codigo:	"46620"	,Valores:	"Venta al por mayor de metales y minerales metalíferos"	},	
	{Codigo:	"46631"	,Valores:	"Venta al por mayor de puertas, ventanas, vitrinas y similares"	},	
	{Codigo:	"46632"	,Valores:	"Venta al por mayor de artículos de ferretería y pinturerías"	},	
	{Codigo:	"46633"	,Valores:	"Vidrierías"	},	
	{Codigo:	"46634"	,Valores:	"Venta al por mayor de maderas"	},	
	{Codigo:	"46639"	,Valores:	"Venta al por mayor de materiales para la construcción n.c.p."	},	
	{Codigo:	"46691"	,Valores:	"Venta al por mayor de sal industrial sin yodar"	},	
	{Codigo:	"46692"	,Valores:	"Venta al por mayor de productos intermedios y desechos de origen textil"	},	
	{Codigo:	"46693"	,Valores:	"Venta al por mayor de productos intermedios y desechos de origen metálico"	},	
	{Codigo:	"46694"	,Valores:	"Venta al por mayor de productos intermedios y desechos de papel y cartón"	},	
	{Codigo:	"46695"	,Valores:	"Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares"	},	
	{Codigo:	"46696"	,Valores:	"Venta al por mayor de productos intermedios y desechos de origen plástico"	},	
	{Codigo:	"46697"	,Valores:	"Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes"	},	
	{Codigo:	"46698"	,Valores:	"Venta de productos intermedios y desechos de origen químico y de caucho"	},	
	{Codigo:	"46699"	,Valores:	"Venta al por mayor de productos intermedios y desechos ncp"	},	
	{Codigo:	"46701"	,Valores:	"Venta de algodón en oro"	},	
	{Codigo:	"46900"	,Valores:	"Venta al por mayor de otros productos"	},	
	{Codigo:	"46901"	,Valores:	"Venta al por mayor de cohetes y otros productos pirotécnicos"	},	
	{Codigo:	"46902"	,Valores:	"Venta al por mayor de artículos diversos para consumo humano"	},	
	{Codigo:	"46903"	,Valores:	"Venta al por mayor de armas de fuego, municiones y accesorios"	},	
	{Codigo:	"46904"	,Valores:	"Venta al por mayor de toldos y tiendas de campaña de cualquier material"	},	
	{Codigo:	"46905"	,Valores:	"Venta al por mayor de exhibidores publicitarios y rótulos"	},	
	{Codigo:	"46906"	,Valores:	"Venta al por mayor de artículos promocionales  diversos"	},	
	{Codigo:	"47111"	,Valores:	"Venta en supermercados"	},	
	{Codigo:	"47112"	,Valores:	"Venta en tiendas de artículos de primera necesidad"	},	
	{Codigo:	"47119"	,Valores:	"Almacenes (venta de diversos artículos)"	},	
	{Codigo:	"47190"	,Valores:	"Venta al por menor de otros productos en comercios no especializados"	},	
	{Codigo:	"47199"	,Valores:	"Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco"	},	
	{Codigo:	"47211"	,Valores:	"Venta al por menor  de frutas y hortalizas"	},	
	{Codigo:	"47212"	,Valores:	"Venta al por menor de carnes, embutidos y productos de granja"	},	
	{Codigo:	"47213"	,Valores:	"Venta al por menor de pescado y mariscos"	},	
	{Codigo:	"47214"	,Valores:	"Venta al por menor de productos  lácteos"	},	
	{Codigo:	"47215"	,Valores:	"Venta al por menor de productos de panadería, repostería y galletas"	},	
	{Codigo:	"47216"	,Valores:	"Venta al por menor de huevos"	},	
	{Codigo:	"47217"	,Valores:	"Venta al por menor de carnes y productos cárnicos"	},	
	{Codigo:	"47218"	,Valores:	"Venta al por menor  de granos básicos y otros"	},	
	{Codigo:	"47219"	,Valores:	"Venta al por menor de alimentos n.c.p."	},	
	{Codigo:	"47221"	,Valores:	"Venta al por menor de hielo"	},	
	{Codigo:	"47223"	,Valores:	"Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento"	},	
	{Codigo:	"47224"	,Valores:	"Venta de bebidas alcohólicas, para su consumo fuera del establecimiento"	},	
	{Codigo:	"47225"	,Valores:	"Venta de bebidas alcohólicas para su consumo dentro del establecimiento"	},	
	{Codigo:	"47230"	,Valores:	"Venta al por menor de tabaco"	},	
	{Codigo:	"47300"	,Valores:	"Venta de combustibles, lubricantes y otros (gasolineras)"	},	
	{Codigo:	"47411"	,Valores:	"Venta al por menor de computadoras y equipo periférico"	},	
	{Codigo:	"47412"	,Valores:	"Venta de equipo y accesorios de telecomunicación"	},	
	{Codigo:	"47420"	,Valores:	"Venta al por menor de equipo de audio y video"	},	
	{Codigo:	"47510"	,Valores:	"Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p."	},	
	{Codigo:	"47521"	,Valores:	"Venta al por menor de productos de madera"	},	
	{Codigo:	"47522"	,Valores:	"Venta al por menor de artículos de ferretería"	},	
	{Codigo:	"47523"	,Valores:	"Venta al por menor de productos de pinturerías"	},	
	{Codigo:	"47524"	,Valores:	"Venta al por menor en vidrierías"	},	
	{Codigo:	"47529"	,Valores:	"Venta al por menor de materiales de construcción y artículos conexos"	},	
	{Codigo:	"47530"	,Valores:	"Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios  especializados"	},	
	{Codigo:	"47591"	,Valores:	"Venta al por menor de muebles"	},	
	{Codigo:	"47592"	,Valores:	"Venta al por menor de artículos de bazar"	},	
	{Codigo:	"47593"	,Valores:	"Venta al por menor de aparatos electrodomésticos, repuestos y accesorios"	},	
	{Codigo:	"47594"	,Valores:	"Venta al por menor de artículos eléctricos y de iluminación"	},	
	{Codigo:	"47598"	,Valores:	"Venta al por menor de instrumentos musicales"	},	
	{Codigo:	"47610"	,Valores:	"Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados"	},	
	{Codigo:	"47620"	,Valores:	"Venta al por menor de discos láser, cassettes, cintas de video y otros"	},	
	{Codigo:	"47630"	,Valores:	"Venta al por menor de productos y equipos de deporte"	},	
	{Codigo:	"47631"	,Valores:	"Venta al por menor de bicicletas, accesorios y repuestos"	},	
	{Codigo:	"47640"	,Valores:	"Venta al por menor de juegos y juguetes  en comercios especializados"	},	
	{Codigo:	"47711"	,Valores:	"Venta al por menor de prendas de vestir y accesorios de vestir"	},	
	{Codigo:	"47712"	,Valores:	"Venta al por menor de calzado"	},	
	{Codigo:	"47713"	,Valores:	"Venta al por menor de artículos de peletería, marroquinería y talabartería"	},	
	{Codigo:	"47721"	,Valores:	"Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario"	},	
	{Codigo:	"47722"	,Valores:	"Venta al por menor de productos cosméticos y de tocador"	},	
	{Codigo:	"47731"	,Valores:	"Venta al por menor de productos de joyería, bisutería, óptica, relojería"	},	
	{Codigo:	"47732"	,Valores:	"Venta al por menor de plantas, semillas, animales y artículos conexos"	},	
	{Codigo:	"47733"	,Valores:	"Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)"	},	
	{Codigo:	"47734"	,Valores:	"Venta al por menor de artesanías, artículos cerámicos y recuerdos en general"	},	
	{Codigo:	"47735"	,Valores:	"Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general"	},	
	{Codigo:	"47736"	,Valores:	"Venta al por menor de armas de fuego, municiones y accesorios"	},	
	{Codigo:	"47737"	,Valores:	"Venta al por menor de artículos de cohetería y pirotécnicos"	},	
	{Codigo:	"47738"	,Valores:	"Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.)"	},	
	{Codigo:	"47739"	,Valores:	"Venta al por menor de otros productos  n.c.p."	},	
	{Codigo:	"47741"	,Valores:	"Venta al por menor de artículos usados"	},	
	{Codigo:	"47742"	,Valores:	"Venta al por menor de textiles y confecciones usados"	},	
	{Codigo:	"47743"	,Valores:	"Venta al por menor de libros, revistas, papel y cartón usados"	},	
	{Codigo:	"47749"	,Valores:	"Venta al por menor de productos usados n.c.p."	},	
	{Codigo:	"47811"	,Valores:	"Venta al por menor de frutas, verduras y hortalizas"	},	
	{Codigo:	"47814"	,Valores:	"Venta al por menor de productos lácteos"	},	
	{Codigo:	"47815"	,Valores:	"Venta al por menor de productos de panadería, galletas y similares"	},	
	{Codigo:	"47816"	,Valores:	"Venta al por menor de bebidas"	},	
	{Codigo:	"47818"	,Valores:	"Venta al por menor en tiendas de mercado y puestos"	},	
	{Codigo:	"47821"	,Valores:	"Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias"	},	
	{Codigo:	"47822"	,Valores:	"Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias"	},	
	{Codigo:	"47823"	,Valores:	"Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias"	},	
	{Codigo:	"47824"	,Valores:	"Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias"	},	
	{Codigo:	"47825"	,Valores:	"Venta al por menor de ropa usada"	},	
	{Codigo:	"47826"	,Valores:	"Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias"	},	
	{Codigo:	"47827"	,Valores:	"Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias"	},	
	{Codigo:	"47829"	,Valores:	"Venta al por menor de artículos textiles ncp en puestos de mercados y ferias"	},	
	{Codigo:	"47891"	,Valores:	"Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados"	},	
	{Codigo:	"47892"	,Valores:	"Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados"	},	
	{Codigo:	"47893"	,Valores:	"Venta al por menor de artículos de bazar en puestos de ferias y mercados"	},	
	{Codigo:	"47894"	,Valores:	"Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados"	},	
	{Codigo:	"47895"	,Valores:	"Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados"	},	
	{Codigo:	"47896"	,Valores:	"Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados"	},	
	{Codigo:	"47899"	,Valores:	"Venta al por menor en puestos de ferias y mercados n.c.p."	},	
	{Codigo:	"47910"	,Valores:	"Venta al por menor por correo o Internet"	},	
	{Codigo:	"47990"	,Valores:	"Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado"	},	
	{Codigo:	"49110"	,Valores:	"Transporte interurbano de pasajeros  por ferrocarril"	},	
	{Codigo:	"49120"	,Valores:	"Transporte de carga por ferrocarril"	},	
	{Codigo:	"49211"	,Valores:	"Transporte de pasajeros urbanos e interurbano mediante buses"	},	
	{Codigo:	"49212"	,Valores:	"Transporte de pasajeros interdepartamental mediante microbuses"	},	
	{Codigo:	"49213"	,Valores:	"Transporte de pasajeros urbanos e interurbano mediante microbuses"	},	
	{Codigo:	"49214"	,Valores:	"Transporte de pasajeros interdepartamental mediante buses"	},	
	{Codigo:	"49221"	,Valores:	"Transporte internacional de pasajeros"	},	
	{Codigo:	"49222"	,Valores:	"Transporte de pasajeros mediante taxis y autos con chofer"	},	
	{Codigo:	"49223"	,Valores:	"Transporte escolar"	},	
	{Codigo:	"49225"	,Valores:	"Transporte de pasajeros para excursiones"	},	
	{Codigo:	"49226"	,Valores:	"Servicios de transporte de personal"	},	
	{Codigo:	"49229"	,Valores:	"Transporte de pasajeros por vía terrestre ncp"	},	
	{Codigo:	"49231"	,Valores:	"Transporte de carga urbano"	},	
	{Codigo:	"49232"	,Valores:	"Transporte nacional de carga"	},	
	{Codigo:	"49233"	,Valores:	"Transporte de carga  internacional"	},	
	{Codigo:	"49234"	,Valores:	"Servicios de  mudanza"	},	
	{Codigo:	"49235"	,Valores:	"Alquiler de vehículos de carga con conductor"	},	
	{Codigo:	"49300"	,Valores:	"Transporte por oleoducto o gasoducto"	},	
	{Codigo:	"50110"	,Valores:	"Transporte de pasajeros marítimo y de cabotaje"	},	
	{Codigo:	"50120"	,Valores:	"Transporte de carga marítimo y de cabotaje"	},	
	{Codigo:	"50211"	,Valores:	"Transporte de pasajeros por vías de navegación interiores"	},	
	{Codigo:	"50212"	,Valores:	"Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor"	},	
	{Codigo:	"50220"	,Valores:	"Transporte de carga por vías de navegación interiores"	},	
	{Codigo:	"51100"	,Valores:	"Transporte aéreo de pasajeros"	},	
	{Codigo:	"51201"	,Valores:	"Transporte de carga por vía aérea"	},	
	{Codigo:	"51202"	,Valores:	"Alquiler de equipo de aerotransporte  con operadores para el propósito de transportar carga"	},	
	{Codigo:	"52101"	,Valores:	"Alquiler de instalaciones de almacenamiento en zonas francas"	},	
	{Codigo:	"52102"	,Valores:	"Alquiler de silos para conservación y almacenamiento de granos"	},	
	{Codigo:	"52103"	,Valores:	"Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos"	},	
	{Codigo:	"52109"	,Valores:	"Alquiler de bodegas para almacenamiento y depósito n.c.p."	},	
	{Codigo:	"52211"	,Valores:	"Servicio de garaje y estacionamiento"	},	
	{Codigo:	"52212"	,Valores:	"Servicios de terminales para el transporte por vía terrestre"	},	
	{Codigo:	"52219"	,Valores:	"Servicios para el transporte por vía terrestre n.c.p."	},	
	{Codigo:	"52220"	,Valores:	"Servicios para el transporte acuático"	},	
	{Codigo:	"52230"	,Valores:	"Servicios para el transporte aéreo"	},	
	{Codigo:	"52240"	,Valores:	"Manipulación de carga"	},	
	{Codigo:	"52290"	,Valores:	"Servicios para el transporte ncp"	},	
	{Codigo:	"52291"	,Valores:	"Agencias de tramitaciones aduanales"	},	
	{Codigo:	"53100"	,Valores:	"Servicios de  correo nacional"	},	
	{Codigo:	"53200"	,Valores:	"Actividades de correo distintas a las actividades postales nacionales"	},	
	{Codigo:	"53201"	,Valores:	"Agencia privada de correo y encomiendas"	},	
	{Codigo:	"55101"	,Valores:	"Actividades de alojamiento para estancias cortas"	},	
	{Codigo:	"55102"	,Valores:	"Hoteles"	},	
	{Codigo:	"55200"	,Valores:	"Actividades de campamentos, parques de vehículos de recreo y parques de caravanas"	},	
	{Codigo:	"55900"	,Valores:	"Alojamiento n.c.p."	},	
	{Codigo:	"56101"	,Valores:	"Restaurantes"	},	
	{Codigo:	"56106"	,Valores:	"Pupusería"	},	
	{Codigo:	"56107"	,Valores:	"Actividades varias de restaurantes"	},	
	{Codigo:	"56108"	,Valores:	"Comedores"	},	
	{Codigo:	"56109"	,Valores:	"Merenderos ambulantes"	},	
	{Codigo:	"56210"	,Valores:	"Preparación de comida para eventos especiales"	},	
	{Codigo:	"56291"	,Valores:	"Servicios de provisión de comidas por contrato"	},	
	{Codigo:	"56292"	,Valores:	"Servicios de concesión de cafetines y chalet en empresas e instituciones"	},	
	{Codigo:	"56299"	,Valores:	"Servicios de preparación de comidas ncp"	},	
	{Codigo:	"56301"	,Valores:	"Servicio de expendio de bebidas en salones y bares"	},	
	{Codigo:	"56302"	,Valores:	"Servicio de expendio de bebidas en puestos callejeros, mercados y ferias"	},	
	{Codigo:	"58110"	,Valores:	"Edición de libros, folletos, partituras y otras ediciones distintas a estas"	},	
	{Codigo:	"58120"	,Valores:	"Edición de directorios y listas de correos"	},	
	{Codigo:	"58130"	,Valores:	"Edición de periódicos, revistas y otras publicaciones periódicas"	},	
	{Codigo:	"58190"	,Valores:	"Otras actividades de edición"	},	
	{Codigo:	"58200"	,Valores:	"Edición de programas informáticos (software)"	},	
	{Codigo:	"59110"	,Valores:	"Actividades de producción cinematográfica"	},	
	{Codigo:	"59120"	,Valores:	"Actividades de post producción de películas, videos y programas  de televisión"	},	
	{Codigo:	"59130"	,Valores:	"Actividades de distribución de películas cinematográficas, videos y programas de televisión"	},	
	{Codigo:	"59140"	,Valores:	"Actividades de exhibición de películas cinematográficas y cintas de vídeo"	},	
	{Codigo:	"59200"	,Valores:	"Actividades de edición y grabación de música"	},	
	{Codigo:	"60100"	,Valores:	"Servicios de difusiones de radio"	},	
	{Codigo:	"60201"	,Valores:	"Actividades de programación y difusión de televisión abierta"	},	
	{Codigo:	"60202"	,Valores:	"Actividades de suscripción y difusión de televisión por cable y/o suscripción"	},	
	{Codigo:	"60299"	,Valores:	"Servicios de televisión, incluye televisión por cable"	},	
	{Codigo:	"60900"	,Valores:	"Programación y transmisión de radio y televisión"	},	
	{Codigo:	"61101"	,Valores:	"Servicio de telefonía"	},	
	{Codigo:	"61102"	,Valores:	"Servicio de Internet "	},	
	{Codigo:	"61103"	,Valores:	"Servicio de telefonía fija"	},	
	{Codigo:	"61109"	,Valores:	"Servicio de Internet n.c.p."	},	
	{Codigo:	"61201"	,Valores:	"Servicios de telefonía celular"	},	
	{Codigo:	"61202"	,Valores:	"Servicios de Internet inalámbrico"	},	
	{Codigo:	"61209"	,Valores:	"Servicios de telecomunicaciones inalámbrico n.c.p."	},	
	{Codigo:	"61301"	,Valores:	"Telecomunicaciones satelitales"	},	
	{Codigo:	"61309"	,Valores:	"Comunicación vía satélite n.c.p."	},	
	{Codigo:	"61900"	,Valores:	"Actividades de telecomunicación n.c.p."	},	
	{Codigo:	"62010"	,Valores:	"Programación Informática"	},	
	{Codigo:	"62020"	,Valores:	"Consultorías y gestión de servicios informáticos"	},	
	{Codigo:	"62090"	,Valores:	"Otras actividades de tecnología de información y servicios de computadora"	},	
	{Codigo:	"63110"	,Valores:	"Procesamiento de datos y actividades relacionadas"	},	
	{Codigo:	"63120"	,Valores:	"Portales WEB"	},	
	{Codigo:	"63910"	,Valores:	"Servicios de Agencias de Noticias"	},	
	{Codigo:	"63990"	,Valores:	"Otros servicios de información  n.c.p."	},	
	{Codigo:	"64110"	,Valores:	"Servicios provistos por el Banco Central de El salvador"	},	
	{Codigo:	"64190"	,Valores:	"Bancos"	},	
	{Codigo:	"64192"	,Valores:	"Entidades dedicadas al envío de remesas"	},	
	{Codigo:	"64199"	,Valores:	"Otras entidades financieras"	},	
	{Codigo:	"64200"	,Valores:	"Actividades de sociedades de cartera"	},	
	{Codigo:	"64300"	,Valores:	"Fideicomisos, fondos y otras fuentes de financiamiento"	},	
	{Codigo:	"64910"	,Valores:	"Arrendamiento financieros"	},	
	{Codigo:	"64920"	,Valores:	"Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera"	},	
	{Codigo:	"64921"	,Valores:	"Instituciones emisoras de tarjetas de crédito y otros"	},	
	{Codigo:	"64922"	,Valores:	"Tipos de crédito ncp"	},	
	{Codigo:	"64928"	,Valores:	"Prestamistas y casas de empeño"	},	
	{Codigo:	"64990"	,Valores:	"Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p."	},	
	{Codigo:	"65110"	,Valores:	"Planes de seguros de vida"	},	
	{Codigo:	"65120"	,Valores:	"Planes de seguro excepto de vida"	},	
	{Codigo:	"65199"	,Valores:	"Seguros generales de todo tipo"	},	
	{Codigo:	"65200"	,Valores:	"Planes se seguro"	},	
	{Codigo:	"65300"	,Valores:	"Planes de pensiones"	},	
	{Codigo:	"66110"	,Valores:	"Administración de mercados financieros (Bolsa de Valores)"	},	
	{Codigo:	"66120"	,Valores:	"Actividades bursátiles (Corredores de Bolsa)"	},	
	{Codigo:	"66190"	,Valores:	"Actividades auxiliares de la intermediación financiera ncp"	},	
	{Codigo:	"66210"	,Valores:	"Evaluación de riesgos y daños"	},	
	{Codigo:	"66220"	,Valores:	"Actividades de agentes y corredores de seguros"	},	
	{Codigo:	"66290"	,Valores:	"Otras actividades auxiliares de seguros y fondos de pensiones"	},	
	{Codigo:	"66300"	,Valores:	"Actividades de administración de fondos"	},	
	{Codigo:	"68101"	,Valores:	"Servicio de alquiler y venta de lotes en cementerios"	},	
	{Codigo:	"68109"	,Valores:	"Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p."	},	
	{Codigo:	"68200"	,Valores:	"Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata"	},	
	{Codigo:	"69100"	,Valores:	"Actividades jurídicas"	},	
	{Codigo:	"69200"	,Valores:	"Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos"	},	
	{Codigo:	"70100"	,Valores:	"Actividades de oficinas centrales de sociedades de cartera"	},	
	{Codigo:	"70200"	,Valores:	"Actividades de consultoría en gestión empresarial"	},	
	{Codigo:	"71101"	,Valores:	"Servicios de arquitectura y planificación urbana y servicios conexos"	},	
	{Codigo:	"71102"	,Valores:	"Servicios de ingeniería"	},	
	{Codigo:	"71103"	,Valores:	"Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos"	},	
	{Codigo:	"71200"	,Valores:	"Ensayos y análisis técnicos"	},	
	{Codigo:	"72100"	,Valores:	"Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería"	},	
	{Codigo:	"72199"	,Valores:	"Investigaciones científicas"	},	
	{Codigo:	"72200"	,Valores:	"Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo"	},	
	{Codigo:	"73100"	,Valores:	"Publicidad"	},	
	{Codigo:	"73200"	,Valores:	"Investigación de mercados y realización de encuestas de opinión pública"	},	
	{Codigo:	"74100"	,Valores:	"Actividades de diseño especializado"	},	
	{Codigo:	"74200"	,Valores:	"Actividades de fotografía"	},	
	{Codigo:	"74900"	,Valores:	"Servicios profesionales y científicos ncp"	},	
	{Codigo:	"75000"	,Valores:	"Actividades veterinarias"	},	
	{Codigo:	"77101"	,Valores:	"Alquiler de equipo de transporte terrestre"	},	
	{Codigo:	"77102"	,Valores:	"Alquiler de equipo de transporte acuático"	},	
	{Codigo:	"77103"	,Valores:	"Alquiler de equipo de transporte  por vía aérea"	},	
	{Codigo:	"77210"	,Valores:	"Alquiler y arrendamiento de equipo de recreo y deportivo"	},	
	{Codigo:	"77220"	,Valores:	"Alquiler de cintas de video y discos"	},	
	{Codigo:	"77290"	,Valores:	"Alquiler de otros efectos personales y enseres domésticos"	},	
	{Codigo:	"77300"	,Valores:	"Alquiler de maquinaria y equipo"	},	
	{Codigo:	"77400"	,Valores:	"Arrendamiento de productos de propiedad intelectual"	},	
	{Codigo:	"78100"	,Valores:	"Obtención y dotación de personal"	},	
	{Codigo:	"78200"	,Valores:	"Actividades de las agencias de trabajo temporal"	},	
	{Codigo:	"78300"	,Valores:	"Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos"	},	
	{Codigo:	"79110"	,Valores:	"Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas"	},	
	{Codigo:	"79120"	,Valores:	"Actividades de los operadores turísticos"	},	
	{Codigo:	"79900"	,Valores:	"Otros servicios de reservas y actividades relacionadas"	},	
	{Codigo:	"80100"	,Valores:	"Servicios de seguridad privados"	},	
	{Codigo:	"80201"	,Valores:	"Actividades de servicios de sistemas de seguridad"	},	
	{Codigo:	"80202"	,Valores:	"Actividades para la prestación de sistemas de seguridad"	},	
	{Codigo:	"80300"	,Valores:	"Actividades de investigación"	},	
	{Codigo:	"81100"	,Valores:	"Actividades combinadas de mantenimiento de edificios e instalaciones"	},	
	{Codigo:	"81210"	,Valores:	"Limpieza general de edificios"	},	
	{Codigo:	"81290"	,Valores:	"Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp"	},	
	{Codigo:	"81300"	,Valores:	"Servicio de jardinería"	},	
	{Codigo:	"82110"	,Valores:	"Servicios administrativos de oficinas"	},	
	{Codigo:	"82190"	,Valores:	"Servicio de fotocopiado y similares, excepto en imprentas"	},	
	{Codigo:	"82200"	,Valores:	"Actividades de las centrales de llamadas (call center)"	},	
	{Codigo:	"82300"	,Valores:	"Organización de convenciones y ferias de negocios"	},	
	{Codigo:	"82910"	,Valores:	"Actividades de agencias de cobro y oficinas de crédito"	},	
	{Codigo:	"82921"	,Valores:	"Servicios de envase y empaque de productos alimenticios"	},	
	{Codigo:	"82922"	,Valores:	"Servicios de envase y empaque de productos medicinales"	},	
	{Codigo:	"82929"	,Valores:	"Servicio de envase y empaque ncp"	},	
	{Codigo:	"82990"	,Valores:	"Actividades de apoyo empresariales ncp"	},	
	{Codigo:	"84110"	,Valores:	"Actividades de la Administración Pública en general"	},	
	{Codigo:	"84111"	,Valores:	"Alcaldías Municipales"	},	
	{Codigo:	"84120"	,Valores:	"Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social"	},	
	{Codigo:	"84130"	,Valores:	"Regulación y facilitación de la actividad económica"	},	
	{Codigo:	"84210"	,Valores:	"Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores"	},	
	{Codigo:	"84220"	,Valores:	"Actividades de defensa"	},	
	{Codigo:	"84230"	,Valores:	"Actividades de mantenimiento del orden público y de seguridad"	},	
	{Codigo:	"84300"	,Valores:	"Actividades de planes de seguridad social de afiliación obligatoria"	},	
	{Codigo:	"85101"	,Valores:	"Guardería educativa"	},	
	{Codigo:	"85102"	,Valores:	"Enseñanza preescolar o parvularia"	},	
	{Codigo:	"85103"	,Valores:	"Enseñanza primaria"	},	
	{Codigo:	"85104"	,Valores:	"Servicio de educación preescolar y primaria integrada"	},	
	{Codigo:	"85211"	,Valores:	"Enseñanza secundaria tercer ciclo (7°, 8° y 9° )"	},	
	{Codigo:	"85212"	,Valores:	"Enseñanza secundaria  de formación general  bachillerato"	},	
	{Codigo:	"85221"	,Valores:	"Enseñanza secundaria de formación técnica y profesional"	},	
	{Codigo:	"85222"	,Valores:	"Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria"	},	
	{Codigo:	"85301"	,Valores:	"Enseñanza superior universitaria"	},	
	{Codigo:	"85302"	,Valores:	"Enseñanza superior no universitaria"	},	
	{Codigo:	"85303"	,Valores:	"Enseñanza superior integrada a educación secundaria y/o primaria"	},	
	{Codigo:	"85410"	,Valores:	"Educación deportiva y recreativa"	},	
	{Codigo:	"85420"	,Valores:	"Educación cultural"	},	
	{Codigo:	"85490"	,Valores:	"Otros tipos de enseñanza n.c.p."	},	
	{Codigo:	"85499"	,Valores:	"Enseñanza formal"	},	
	{Codigo:	"85500"	,Valores:	"Servicios de apoyo a la enseñanza"	},	
	{Codigo:	"86100"	,Valores:	"Actividades de hospitales"	},	
	{Codigo:	"86201"	,Valores:	"Clínicas médicas"	},	
	{Codigo:	"86202"	,Valores:	"Servicios de Odontología"	},	
	{Codigo:	"86203"	,Valores:	"Servicios médicos"	},	
	{Codigo:	"86901"	,Valores:	"Servicios de análisis y estudios de diagnóstico"	},	
	{Codigo:	"86902"	,Valores:	"Actividades de atención de la salud humana"	},	
	{Codigo:	"86909"	,Valores:	"Otros Servicio relacionados con la salud ncp"	},	
	{Codigo:	"87100"	,Valores:	"Residencias de ancianos con atención de enfermería"	},	
	{Codigo:	"87200"	,Valores:	"Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas"	},	
	{Codigo:	"87300"	,Valores:	"Instituciones dedicadas al cuidado de ancianos y discapacitados"	},	
	{Codigo:	"87900"	,Valores:	"Actividades de asistencia a niños y jóvenes"	},	
	{Codigo:	"87901"	,Valores:	"Otras actividades de atención en instituciones"	},	
	{Codigo:	"88100"	,Valores:	"Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados"	},	
	{Codigo:	"88900"	,Valores:	"servicios sociales sin alojamiento ncp"	},	
	{Codigo:	"90000"	,Valores:	"Actividades creativas artísticas y de esparcimiento"	},	
	{Codigo:	"91010"	,Valores:	"Actividades de bibliotecas y archivos"	},	
	{Codigo:	"91020"	,Valores:	"Actividades de museos y preservación de lugares y edificios históricos"	},	
	{Codigo:	"91030"	,Valores:	"Actividades de jardines botánicos, zoológicos y de reservas naturales"	},	
	{Codigo:	"92000"	,Valores:	"Actividades de juegos y apuestas"	},	
	{Codigo:	"93110"	,Valores:	"Gestión de instalaciones deportivas"	},	
	{Codigo:	"93120"	,Valores:	"Actividades de clubes deportivos"	},	
	{Codigo:	"93190"	,Valores:	"Otras actividades deportivas"	},	
	{Codigo:	"93210"	,Valores:	"Actividades de parques de atracciones y parques temáticos"	},	
	{Codigo:	"93291"	,Valores:	"Discotecas y salas de baile"	},	
	{Codigo:	"93298"	,Valores:	"Centros vacacionales"	},	
	{Codigo:	"93299"	,Valores:	"Actividades de esparcimiento ncp"	},	
	{Codigo:	"94110"	,Valores:	"Actividades de organizaciones empresariales y de empleadores"	},	
	{Codigo:	"94120"	,Valores:	"Actividades de organizaciones profesionales"	},	
	{Codigo:	"94200"	,Valores:	"Actividades de sindicatos"	},	
	{Codigo:	"94910"	,Valores:	"Actividades de organizaciones religiosas"	},	
	{Codigo:	"94920"	,Valores:	"Actividades de organizaciones políticas"	},	
	{Codigo:	"94990"	,Valores:	"Actividades de asociaciones n.c.p."	},	
	{Codigo:	"95110"	,Valores:	"Reparación de computadoras y equipo periférico"	},	
	{Codigo:	"95120"	,Valores:	"Reparación de equipo de comunicación"	},	
	{Codigo:	"95210"	,Valores:	"Reparación de aparatos electrónicos de consumo"	},	
	{Codigo:	"95220"	,Valores:	"Reparación de aparatos doméstico y equipo de hogar y jardín"	},	
	{Codigo:	"95230"	,Valores:	"Reparación de calzado y artículos de cuero"	},	
	{Codigo:	"95240"	,Valores:	"Reparación de muebles y accesorios para el hogar"	},	
	{Codigo:	"95291"	,Valores:	"Reparación de Instrumentos musicales"	},	
	{Codigo:	"95292"	,Valores:	"Servicios de cerrajería y copiado de llaves"	},	
	{Codigo:	"95293"	,Valores:	"Reparación de joyas y relojes"	},	
	{Codigo:	"95294"	,Valores:	"Reparación de bicicletas, sillas de ruedas y rodados n.c.p."	},	
	{Codigo:	"95299"	,Valores:	"Reparaciones de enseres personales n.c.p."	},	
	{Codigo:	"96010"	,Valores:	"Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco"	},	
	{Codigo:	"96020"	,Valores:	"Peluquería y otros tratamientos de belleza"	},	
	{Codigo:	"96030"	,Valores:	"Pompas fúnebres y actividades conexas"	},	
	{Codigo:	"96091"	,Valores:	"Servicios de sauna y otros servicios para la estética corporal n.c.p."	},	
	{Codigo:	"96092"	,Valores:	"Servicios n.c.p."	},	
	{Codigo:	"97000"	,Valores:	"Actividad de los hogares en calidad de empleadores de personal doméstico"	},	
	{Codigo:	"98100"	,Valores:	"Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio"	},	
	{Codigo:	"98200"	,Valores:	"Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio"	},	
	{Codigo:	"99000"	,Valores:	"Actividades de organizaciones y órganos extraterritoriales"	},	
	{Codigo:	"10001"	,Valores:	"Empleados"	},	
	{Codigo:	"10002"	,Valores:	"Pensionado"	},	
	{Codigo:	"10003"	,Valores:	"Estudiante"	},	
	{Codigo:	"10004"	,Valores:	"Desempleado"	},	
	{Codigo:	"10005"	,Valores:	"Otros"	},	
	{Codigo:	"10006"	,Valores:	"Comerciante"	},	
]

//---[PAISES]
const cat020 = [ 
  { id: 187, Codigo: "9300", Valores: "EL SALVADOR" }, 
];

//---[ Otros Documentos Asociados]
const cat021 = [
  { Codigo: 1, Valores: "Emisor" },
  { Codigo: 2, Valores: "Receptor" },
  { Codigo: 3, Valores: "Médico" },
  { Codigo: 4, Valores: "Transporte" },
];

//---[ Tipo de documento de identificación del Receptor ]
const cat022 = [
  { Codigo: "36", Valores: "NIT" },
  { Codigo: "13", Valores: "DUI" },
  { Codigo: "37", Valores: "Otro" },
  { Codigo: "03", Valores: "Pasaporte" },
  { Codigo: "02", Valores: "Carnet de Residente" },
];

const Catalogos = {
  cat001, cat002, cat003, cat004, cat005, cat006, cat007, cat009, cat010,
  cat011, cat012, cat013, cat014, cat015, cat016, cat017, cat018, cat019, cat020,
  cat021, cat022,
};
export default Catalogos; 